# Common Labels
labels:
  app: "health-expense-calculator"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "health-expense-calculator"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "expense_calculator_schema"
    image:
      repository: "health-expense-calculator-db"

# Container Configs
image:
  repository: "health-expense-calculator"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health-expense-calculator/health"
  readinessProbePath: "/health-expense-calculator/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
java-args: ""
cpu_limits: "300m"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /health-expense-calculator
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /health-expense-calculator
  - name: EXPENSE_CALCULATOR_CONSUME_TOPIC
    value: "calculate-musterroll-health"
  - name: EXPENSE_CALCULATOR_ERROR_TOPIC
    value: "calculate-error-health"
  - name: EXPENSE_CALCULATOR_CREATE_BILL_TOPIC
    value: "calculate-billmeta-health"
  - name: EGOV_MUSTERROLL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-muster-roll
  - name: EGOV_BILL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-expense
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "egov-mdms-service/v1/_search"      
  - name: EGOV_IDGEN_HOST
    valueFrom: 
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual
  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2
  {{- if index .Values "egov-mdms-service-endpoint-key" }}
  - name: EGOV_MDMS_SEARCH_V2_ENDPOINT
    value: {{ index .Values "egov-mdms-service-endpoint-key" | quote }} 
  {{- end }}
  - name: WORKS_ATTENDANCE_LOG_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-attendance
  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service
  - name: EGOV_BOUNDARY_SEARCH_URL
    value: {{ index .Values "egov-boundary-search-url" | default "/boundary-service/boundary-relationships/_search" }}
  - name: EGOV_BOUNDARY_HIERARCHY_NAME
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: boundary-hierarchy
  - name: EGOV_LOCALIZATION_LOCALE_CODE
    value: "en_IN"
  - name: PROJECT_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-project
  - name: PROJECT_SEARCH_PATH
    value: "health-project/v1/_search"
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_PDF_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  {{- if index .Values "excell-state-level-tenant-id" }}
  - name: STATE_LEVEL_TENANT_ID
    value: {{ index .Values "excell-state-level-tenant-id" | quote }}
  {{- else }}
  - name: STATE_LEVEL_TENANT_ID
    value: {{ index .Values "state-level-tenant-id" | default "mz" | quote }}
  {{- end }}
  {{- if index .Values "payment-pdf-key" }}
  - name: PAYMENT_PDF_KEY
    value: {{ index .Values "payment-pdf-key" | quote }}
  {{- end }}

  {{- if index .Values "report-localization-module-name" }}
  - name: REPORT_LOCALIZATION_MODULE_NAME
    value: {{ index .Values "report-localization-module-name" | quote }}
  {{- end }}

  {{- if index .Values "report-localization-boundary-module-name" }}
  - name: REPORT_LOCALIZATION_BOUNDARY_MODULE_NAME
    value: {{ index .Values "report-localization-boundary-module-name" | quote }}
  {{- end }}

  {{- if index .Values "report-localization-locale-code" }}
  - name: REPORT_LOCALIZATION_LOCALE_CODE
    value: {{ index .Values "report-localization-locale-code" | quote }}
  {{- end }}

  {{- if index .Values "report-header-title" }}
  - name: REPORT_HEADER_TITLE
    value: {{ index .Values "report-header-title" | quote }}
  {{- end }}

  {{- if index .Values "report-date-time-format" }}
  - name: REPORT_DATE_TIME_FORMAT
    value: {{ index .Values "report-date-time-format" | quote }}
  {{- end }}

  {{- if index .Values "report-date-time-zone" }}
  - name: REPORT_DATE_TIME_ZONE
    value: {{ index .Values "report-date-time-zone" | quote }}
  {{- end }}

  {{- if index .Values "report-error-queue-topic" }}
  - name: REPORT_ERROR_QUEUE_TOPIC
    value: {{ index .Values "report-error-queue-topic" | quote }}
  {{- end }}
  {{- if index .Values "report-retry-queue-topic" }}
  - name: REPORT_RETRY_QUEUE_TOPIC
    value: {{ index .Values "report-retry-queue-topic" | quote }}
  {{- end }}
  {{- if index .Values "expense-bill-create-topic" }}
  - name: EXPENSE_BILLING_BILL_CREATE
    value: {{ index .Values "expense-bill-create-topic" | quote }}
  {{- end }}
  {{- if index .Values "expense-bill-update-topic" }}
  - name: EXPENSE_BILLING_BILL_UPDATE
    value: {{ index .Values "expense-bill-update-topic" | quote }}
  {{- end }}
  {{- if index .Values "expense-bill-index-topic" }}
  - name: EXPENSE_BILLING_BILL_INDEX
    value: {{ index .Values "expense-bill-index-topic" | quote }}
  {{- end }}
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  {{- if index .Values "is-attendance-approval-required" }}
  - name: IS_ATTENDANCE_APPROVAL_REQUIRED
    value: {{ index .Values "is-attendance-approval-required" | quote }}
  {{- end }}
  {{- if index .Values "register-batch-size" }}
  - name: REGISTER_BATCH_SIZE
    value: {{ index .Values "register-batch-size" | quote }}
  {{- end }}
  {{- if index .Values "bill-generation-async-enabled" }}
  - name: BILL_GENERATION_ASYNC_ENABLED
    value: {{ index .Values "bill-generation-async-enabled" | quote }}
  {{- end }}
  {{- if index .Values "bill-generation-async-topic" }}
  - name: BILL_GENERATION_ASYNC_TOPIC
    value: {{ index .Values "bill-generation-async-topic" | quote }}
  {{- end }}
  {{- if index .Values "report-generation-trigger-topic" }}
  - name: REPORT_GENERATION_TRIGGER_TOPIC
    value: {{ index .Values "report-generation-trigger-topic" | quote }}
  {{- end }}
  {{- if index .Values "report-generation-retry-trigger-topic" }}
  - name: REPORT_GENERATION_RETRY_TRIGGER_TOPIC
    value: {{ index .Values "report-generation-retry-trigger-topic" | quote }}
  {{- end }}
  - name: SPRING_DATA_REDIS_HOST
    value: redis.backbone
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: {{ index .Values "spring-kafka-consumer-group-id" | quote }}
  {{- if index .Values "spring-kafka-producer-properties-max-request-size" }}
  - name: SPRING_KAFKA_PRODUCER_PROPERTIES_MAX_REQUEST_SIZE
    value: {{ index .Values "spring-kafka-producer-properties-max-request-size" | quote }} 
  {{- end }}
  - name: WORKS_ATTENDANCE_REGISTER_SEARCH_ENDPOINT
    value: health-attendance/v1/_search
  - name: WORKS_ATTENDANCE_REGISTER_UPDATE_ENDPOINT
    value: health-attendance/v1/_update
  - name: EGOV_MUSTERROLL_SEARCH_ENDPOINT 
    value: {{ index .Values "egov-musterroll-search-endpoint" | quote }} 
  - name: IS_HEALTH_CONTEXT_ENABLED
    value: "true"
  - name: EGOV_INDIVIDUAL_SEARCH_ENDPOINT
    value: "/health-individual/v1/_search"
  - name: EGOV_FILESTORE_PATH
    value: "filestore/v1/files"
  - name: BILLING_FREQUENCY_CUSTOM_MINIMUM_DAYS
    value: {{ index .Values "billing-frequency-custom-minimum-days" | quote }}
  - name: BILLING_CONFIG_V2_ENABLED
    value: {{ index .Values "billing-config-v2-enabled" | default "false" | quote }}
  - name: BILLING_CONFIG_CREATE_TOPIC
    value: {{ index .Values "billing-config-create-topic" | default "billing-config-create" | quote }}
  - name: BILLING_CONFIG_UPDATE_TOPIC
    value: {{ index .Values "billing-config-update-topic" | default "billing-config-update" | quote }}
  - name: BILLING_PERIOD_STATUS_UPDATE_TOPIC
    value: {{ index .Values "billing-period-status-update-topic" | default "billing-period-status-update" | quote }}
  - name: BILLING_PERIOD_GENERATION_ENABLED
    value: {{ index .Values "billing-period-generation-enabled" | default "false" | quote }}
  - name: BILLING_MUSTER_ROLL_PERIOD_AWARE_ENABLED
    value: {{ index .Values "billing-muster-roll-period-aware-enabled" | default "false" | quote }}
  - name: BILLING_V2_BATCH_PROCESSING_ENABLED
    value: "false"
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_UPDATE_TOPIC
    value: {{ index .Values "project-management-system-kafka-update-topic" | default "update-project" | quote }}
  - name: PROJECT_MANAGEMENT_SYSTEM_KAFKA_UPDATE_DATE_TOPIC
    value: {{ index .Values "project-management-system-kafka-update-date-topic" | default "update-project-date" | quote }}
  - name: EGOV_WORKS_EXPENSE_WAGE_BUSINESS_SERVICE
    value: "EXPENSE.WAGES"
  - name: EGOV_HRMS_SEARCH_ENDPOINT
    value: "/health-hrms/employees/_search"
  - name: STATE_SCHEMA_INDEX_POSITION_TENANTID
    value: "0"
  
