#!/usr/bin/env bash
# Refresh environments/azure-k3s-lnp-tags.yaml from the LnP team's own environment file:
# the image tags the test-lts cluster runs (origin/digit-lts). The LnP images move daily, so
# the overlay pins them from this snapshot instead of by hand. Re-run, review the diff, commit.
#   ./lnp-tags.sh [git-ref]        default: origin/digit-lts
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd); HELM_DIR=$(cd "$HERE/../../.." && pwd)
REF=${1:-origin/digit-lts}
git -C "$HELM_DIR" fetch -q origin digit-lts 2>/dev/null || true
python3 - "$HELM_DIR" "$REF" > "$HELM_DIR/environments/azure-k3s-lnp-tags.yaml" <<'PY'
import subprocess, sys, yaml
helm_dir, ref = sys.argv[1], sys.argv[2]
git = lambda *a: subprocess.run(["git", "-C", helm_dir, *a], check=True, capture_output=True, text=True).stdout
sha = git("rev-parse", "--short", ref).strip()
src = yaml.safe_load(git("show", f"{ref}:deploy-as-code/helm/environments/test-lts.yaml"))
KEYS = ["mdms-v2", "walt", "calculator", "schema-registry", "pdf-v3", "vc",
        "license-certificate", "license-admin", "license-citizen", "license-employee", "license-validator"]
print(f"# GENERATED by scripts/lnp-tags.sh from {ref} ({sha}) — environments/test-lts.yaml, the LnP team's")
print("# own environment. Image tags only; everything else about the overlay lives in azure-k3s-lnp.yaml.gotmpl.")
print("# Layered by lnp-helmfile.yaml BEFORE the gotmpl, so the gotmpl may still override a tag on purpose.")
out = {}
for k in KEYS:
    b = src.get(k) or {}
    img = b.get("image") or {}
    e = {"image": {"tag": str(img.get("tag"))}}
    if img.get("repository"): e["image"]["repository"] = img["repository"]
    init = ((b.get("initContainers") or {}).get("dbMigration") or {}).get("image") or {}
    if init.get("tag"): e["initContainers"] = {"dbMigration": {"image": {"tag": str(init["tag"])}}}
    out[k] = e
print(yaml.safe_dump(out, sort_keys=False), end="")
PY
echo "wrote environments/azure-k3s-lnp-tags.yaml from $REF"
