apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: playground
  namespace: sample-app
spec:
  interval: 5m
  subscriptions:
    - image:
        repoURL: egovio/playground
        imageSelectionStrategy: NewestBuild
        ignoreTagsRegexes:
          - "^latest$"
        discoveryLimit: 10
