# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin enable properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=MockIdaDataProviderPlugin
mosip.certify.plugin-mode=DataProvider

## --------------------------------------------DataProvider specific Certify configuration ---------------------------------------------------
# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration:P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1


## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
# This property is changed from issuer-uri to did-url as all the keys will be hosted on the same did.json file and kid will be appended to it for uniqueness.
mosip.certify.data-provider-plugin.did-url=did:web:inji.github.io:inji-config:dev-int-inji:mock-identity
mosip.certify.mock.authenticator.get-identity-url=https://${mosip.api.mockidentitysystem.host}/v1/mock-identity-system/identity

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.mock.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mosip.esignet.mock.host}
mosip.certify.database.name=inji_certify_mock
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.mock.security.pin:${softhsm.certify.security.pin}}
# Set the key prefix for Redis cache
mosip.certify.cache.redis.key-prefix=${mosip.injicertify.mock.host}::
# Add Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Mock Verifiable Credential',\
    'locale': 'en'\
  }\
}
mosip.certify.indexed-mappings.email=$.email
mosip.certify.indexed-mappings.postalCode=$.postalCode

mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/