# MOSIP

mosipbox.public.url=${mosip.api.internal.url}
mosip.api.internal.url=https://${mosip.api.internal.host}
mosip.api.public.url=https://${mosip.api.public.host}
public.url=${mosip.api.internal.url}/v1/mimoto
mosip.resident.base.url=${mosip.resident.url}/resident/v1
idp.binding.base.url=https://${mosipid.identity.esignet.host}/v1/esignet/binding

# Configurations related to openid4vci
mosip.openid.issuers=mimoto-issuers-config.json
mosip.openid.htmlTemplate=credential-template.html
mosip.oidc.client.assertion.type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
mosip.oidc.p12.filename=oidckeystore.p12
mosip.oidc.p12.password=${mimoto.oidc.keystore.password}
mosip.oidc.p12.path=certs/

logging.level.org.springframework.web.client.RestTemplate=INFO

management.endpoint.env.show-values=ALWAYS
management.endpoints.web.exposure.include=*

#Property to enable VC download using OTP
mosip.otp.download.enable=false

#OpenId4VP related Configuration START

#File name for the mimoto trusted verifiers
mosip.openid.verifiers=mimoto-trusted-verifiers.json

#Inji Web Config

#Host url for the InjiWeb
mosip.inji.web.url=https://${injiweb.host}
#Redirect Url for InjiWeb
mosip.inji.web.redirect.url=${mosip.inji.web.url}/authorize
#Character Length Limit for the QRCode data
mosip.inji.qr.data.size.limit=10000
#Height of the QRCode
mosip.inji.qr.code.height=650
#Width of the QRCode
mosip.inji.qr.code.width=650
mosip.inji.user.wallet.pin.validation.regex=^\\d{6}$
mosip.inji.user.wallet.name.validation.regex=^[A-Za-z0-9 _.-]{1,50}$

#Inji Verify Config

#Online Sharing Authorize URL pattern
mosip.inji.ovp.qrdata.pattern=INJI_OVP://${mosip.inji.web.url}/authorize?response_type=vp_token&resource=%s&presentation_definition=%s
#Online Sharing Redirect URL pattern
mosip.inji.ovp.redirect.url.pattern=%s#vp_token=%s&presentation_submission=%s
#Online Sharing Error URL pattern
mosip.inji.ovp.error.redirect.url.pattern=%s?error=%s&error_description=%s

#DataShare Config

#Host url for the DataShare
mosip.data.share.url=http://${mosip.inji.datashare.host}
#Create url to push the VC into Data share
mosip.data.share.create.url=${mosip.data.share.url}/v1/datashare/create/static-policyid/static-subscriberid
#Retry count to push the VC into Data share
mosip.data.share.create.retry.count=3
#Get url to retrieve the VC from Data share
mosip.data.share.get.url.pattern=${mosip.data.share.url}/v1/datashare/get/static-policyid/static-subscriberid/*

#OpenId4VP related Configuration END

# Platform Properties Start

mosip.websub.url=http://websub.websub
keycloak.internal.url=http://keycloak.keycloak
mosip.kernel.auditmanager.url=http://auditmanager.kernel/
mosip.kernel.masterdata.url=http://masterdata.kernel
keycloak.external.url=https://iam.collab.mosip.net
mosip.kernel.authmanager.url=http://authmanager.kernel

RESIDENT_OTP=${mosip.resident.base.url}/req/otp
RESIDENT_CREDENTIAL_REQUEST=${mosip.resident.base.url}/req/credential
RESIDENT_CREDENTIAL_REQUEST_STATUS=${RESIDENT_CREDENTIAL_REQUEST}/status
RESIDENT_VID=${mosip.resident.base.url}/vid
RESIDENT_AUTH_LOCK=${mosip.resident.base.url}/req/auth-lock
RESIDENT_AUTH_UNLOCK=${mosip.resident.base.url}/req/auth-unlock
RESIDENT_INDIVIDUALID_OTP=${mosip.resident.base.url}/individualId/otp
RESIDENT_AID_GET_INDIVIDUALID=${mosip.resident.base.url}/aid/status
BINDING_OTP=${idp.binding.base.url}/binding-otp
WALLET_BINDING=${idp.binding.base.url}/wallet-binding


# Resident App
credential.template=template.json
credential.sample=sample_credential.json
credential.data.path=data
safetynet.api.key=
safetynet.api.url=https://www.googleapis.com/androidcheck/v1/attestations/verify?key=${safetynet.api.key}

registration.processor.print.textfile=registration-processor-print-text-file.json

# Websub
mosip.event.hubUrl=${mosip.websub.url}/hub/
mosip.event.hub.subUrl=${mosip.event.hubUrl}
mosip.event.hub.pubUrl=${mosip.event.hubUrl}


# MOSIP partner
mosip.partner.id=mpartner-default-mobile
mosip.event.callBackUrl=${public.url}/credentialshare/callback/notify
mosip.event.topic=${mosip.partner.id}/CREDENTIAL_ISSUED
mosip.event.secret=Kslk30SNF2AChs2

mosip.partner.crypto.p12.filename=keystore.p12
mosip.partner.crypto.p12.password=${mosip.partner.crypto.p12.password}
mosip.partner.crypto.p12.alias=partner
mosip.partner.encryption.key=${mosip.partner.crypto.p12.password}
mosip.partner.prependThumbprint=true

mosip.datashare.partner.id=mpartner-default-resident
mosip.datashare.policy.id=mpolicy-default-resident

# CSRF Security Configuration
# List of URLs that are excluded from CSRF protection. These URLs can still require authentication.
mosip.security.csrf-ignore-urls=/oauth2/**,/logout,/safetynet/**,/credentials/**,/credentialshare/**,/binding-otp,/wallet-binding,\
  /get-token/**,/req/otp,/vid,/req/auth/**,/req/individualId/otp,/auth/*/token-login,/wallets/**
# Delayed websub subscription. Default is 5 seconds in ms.
mosip.event.delay-millisecs=5000
# Websub re-subscription workaround for losing subscribed topic when MOSIP websub update or restart. Default is 5 minutes in ms.
websub-resubscription-delay-millisecs=300000

#-------------TOKEN GENERATION----------------
#Token generation request id
token.request.id=io.mosip.registration.processor
#Token generation app id
token.request.appid=regproc
#Token generation username
token.request.username=registrationprocessor
#Token generation password
token.request.password={cipher}b77f8738b7fb8c48f84d587b045fa50099a569c381d1857eddbcd04afd83cd08
#Token generation version
token.request.version=1.0
#Token generation Client Id
token.request.clientId=mosip-regproc-client
#Token generation secret key
token.request.secretKey={cipher}b77f8738b7fb8c48f84d587b045fa50099a569c381d1857eddbcd04afd83cd08
#Token generation issuer url
token.request.issuerUrl=${keycloak.internal.url}/auth/realms/mosip

#Audit Service
AUDIT=${mosip.kernel.auditmanager.url}/v1/auditmanager/audits
AUDIT_URL=${mosip.kernel.auditmanager.url}/v1/auditmanager/audits
KEYBASEDTOKENAPI=${mosip.kernel.authmanager.url}/v1/authmanager/authenticate/clientidsecretkey

#Master Data Services
# MASTER=http://kernel-masterdata-service/v1/masterdata
MASTER=${mosip.kernel.masterdata.url}/v1/masterdata
TEMPLATES=${MASTER}/templates

#Packet receiver application version
mosip.print.application.version=1.0
#Request Date Time format
mosip.print.datetime.pattern=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'


#-------------Printing Service--------------------
mosip.print.service.id=mosip.print

#Audit request id
mosip.print.audit.id=mosip.applicanttype.getApplicantType
mosip.country.code=MOR

#Kernel Crypto signature
registration.processor.signature.isEnabled=true

# Language Supported By Platform - ISO
mosip.supported-languages=eng,ara,fra,khm

mosip.template-language=eng
mosip.optional-languages=ara,fra
mosip.mandatory-languages=eng,khm

# mosip.primary-language=eng
# mosip.secondary-language=ara

#----------------------- CBEFF Util--------------------------------------------------
# Cbeff URL where the files will be stored in git, change it accordingly in case of change of storage location.
mosip.kernel.xsdstorage-uri=https://raw.githubusercontent.com/mosip/mosip-config/develop/
# Cbeff XSD file name in config server
mosip.kernel.xsdfile=mosip-cbeff.xsd

#----------------------------- Applicant Type --------------------------------------------------
mosip.kernel.applicant.type.age.limit = 5

#----------------------------- Static PIN --------------------------------------------------
mosip.kernel.pin.length=6

#-----------------------------TOKEN-ID Properties---------------------------------
#length of the token id
mosip.kernel.tokenid.length=36

#------------------------------------ Key-manager specific properties --------------------------------------------------

#Crypto asymmetric algorithm name
mosip.kernel.crypto.asymmetric-algorithm-name=RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING
#Crypto symmetric algorithm name
mosip.kernel.crypto.symmetric-algorithm-name=AES/GCM/NoPadding
#Encrypted data and encrypted symmetric key separator
mosip.kernel.data-key-splitter=#KEY_SPLITTER#
#GCM tag length
mosip.kernel.crypto.gcm-tag-length=128
#Hash algo name
mosip.kernel.crypto.hash-algorithm-name=PBKDF2WithHmacSHA512
#Symmtric key length used in hash
mosip.kernel.crypto.hash-symmetric-key-length=256
#No of iterations in hash
mosip.kernel.crypto.hash-iteration=10000
mosip.kernel.keygenerator.symmetric-algorithm-name=AES
mosip.kernel.keygenerator.symmetric-key-length=256
#Asymmetric algorithm key length
mosip.kernel.keygenerator.asymmetric-key-length=2048
#Keygenerator asymmetric algorithm name
mosip.kernel.keygenerator.asymmetric-algorithm-name=RSA
mosip.kernel.keymanager.hsm.config-path=/home/mosip/encryption/encryptionkeystore.p12
mosip.kernel.keymanager.hsm.keystore-type=PKCS12
mosip.kernel.keymanager.hsm.keystore-pass=${mimoto.oidc.keystore.password}


mosip.kernel.keymanager.certificate.default.common-name=www.mosip.io
mosip.kernel.keymanager.certificate.default.organizational-unit=IIITB
mosip.kernel.keymanager.certificate.default.organization=IIITB
mosip.kernel.keymanager.certificate.default.location=BANGALORE
mosip.kernel.keymanager.certificate.default.state=KA
mosip.kernel.keymanager.certificate.default.country=IN

mosip.kernel.keymanager.autogen.appids.list=ROOT,BASE,MIMOTO
mosip.kernel.keymanager.autogen.basekeys.list=MIMOTO:user_pii
mosip.kernel.keymgr.hsm.health.check.enabled=false
zkcrypto.random.key.generate.count=0

inji.mimoto.database.hostname=postgres-postgresql.postgres
keymanager.persistence.jdbc.driver=org.postgresql.Driver
keymanager_database_url = jdbc:postgresql://${inji.mimoto.database.hostname}:${inji.mimoto.database.port}/inji_mimoto
keymanager_database_password=${db.dbuser.password}
keymanager_database_username= mimotouser
keymanager.persistence.jdbc.schema=mimoto

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=none
hibernate.jdbc.lob.non_contextual_creation=true
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.connection.charSet=utf8
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false
hibernate.cache.use_structured_entries=false
hibernate.generate_statistics=false
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

# log level
logging.level.root=WARN
logging.level.io.mosip=INFO
# logging.level.io.mosip.kernel.auth.defaultadapter.filter=INFO
logging.level.io.mosip.kernel.auth.defaultadapter=DEBUG
logging.level.org.springframework.http.client=DEBUG
logging.level.io.mosip.residentapp=INFO
logging.level.reactor.netty.http.client=INFO
# tomcat access logs
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=/dev
server.tomcat.accesslog.prefix=stdout
server.tomcat.accesslog.buffered=false
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=
server.tomcat.accesslog.pattern={"@timestamp":"%{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}t","level":"ACCESS","level_value":70000,"traceId":"%{X-B3-TraceId}i","appId":"%{X-AppId}i","statusCode":%s,"req.requestURI":"%U","bytesSent":%b,"timeTaken":%T,"appName":"${spring.application.name}"}
server.tomcat.accesslog.className=io.mosip.kernel.core.logger.config.SleuthValve
registration.processor.unMaskedUin.length=5

IDSchema.Version=1.0
registration.processor.identityjson=identity-mapping.json
registration.processor.demographic.identity=identity
CREATEDATASHARE=${mosip.datashare.url}/v1/datashare/create
DECRYPTPINBASSED=${mosip.kernel.keymanager.url}/v1/keymanager/decryptWithPin

config.server.file.storage.uri=${spring.cloud.config.uri}/${spring.application.name}/${spring.profiles.active}/${spring.cloud.config.label}/


#Auth Adapter rest template authentication configs
mosip.iam.adapter.appid=partner
mosip.iam.adapter.clientid=mpartner-default-mobile
mosip.iam.adapter.clientsecret=${mpartner.default.mobile.secret}
auth.server.admin.issuer.uri=${keycloak.external.url}/auth/realms/

mosip.iam.adapter.issuerURL=${keycloak.internal.url}/auth/realms/mosip
mosip.authmanager.base-url=${mosip.kernel.authmanager.url}/v1/authmanager
mosip.authmanager.client-token-endpoint=${mosip.authmanager.base-url}/authenticate/clientidsecretkey
auth.server.admin.validate.url=${mosip.kernel.authmanager.url}/v1/authmanager/authorize/admin/validateToken


# in minutes
mosip.iam.adapter.validate-expiry-check-rate=1440

# in minutes
mosip.iam.adapter.renewal-before-expiry-interval=1440

#this should be false if you don?t use this restTemplate true if you do

mosip.iam.adapter.self-token-renewal-enable=true
mosip.auth.filter_disable=false
mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.appids.realm.map={prereg:'mosip',ida:'mosip',registrationclient:'mosip',regproc:'mosip',partner:'mosip',resident:'mosip',admin:'mosip',crereq:'mosip',creser:'mosip',datsha:'mosip',idrepo:'mosip'}

vercred.type.vid=VID
mosip.idp.partner.id=mpartner-default-mobile
mosip.idp.partner.encryption.key={cipher}b77f8738b7fb8c48f84d587b045fa50099a569c381d1857eddbcd04afd83cd08
wallet.binding.partner.id=mpartner-default-mimotokeybinding
wallet.binding.partner.api.key=${mimoto.wallet.binding.partner.api.key}

mosip.kernel.masterdata.code.validate.regex=[^a-z0-9\u0600-\u06FF\u0C80-\u0CFF]
mosip.kernel.masterdata.name.validate.regex=[^a-z\u0600-\u06FF\u0C80-\u0CFF] 

#mosip notification otp channel config
mosip.notificationtype=SMS|EMAIL|PHONE

# Platform Properties End

# Wallet Passcode Configuration
# Duration (in minutes) for which the wallet remains locked after exceeding failed attempts in a cycle
wallet.passcode.retryBlockedUntil=1
# Maximum number of failed passcode attempts allowed in a single cycle (defaults to 1 if <=0)
wallet.passcode.maxFailedAttemptsAllowedPerCycle=5
# Maximum number of lock cycles allowed before the wallet is permanently locked (defaults to 1 if <=0)
wallet.passcode.maxLockCyclesAllowed=3

#Signing Algorithms Priority Order Configuration
signing.algorithms.priority.order = ED25519,ES256K,ES256,RS256

# Enables or disables the display of disclosures for VCs
mosip.injiweb.mask.disclosures=true

#Caffeine cache related configurations
# Cache expiry time in minutes for the issuer's well-known endpoint response.
cache.credential-issuer.wellknown.expiry-time-in-min = 60
# Cache expiry time in minutes for issuers configurations read from a config file.
cache.issuers-config.expiry-time-in-min = 60
# Cache expiry time in minutes for the authentication server's well-known endpoint response.
cache.credential-issuer.authserver-wellknown.expiry-time-in-min = 60
# Default cache expiry time in minutes for others cache types
cache.default.expiry-time-in-min = 60
