# Common Labels
labels:
  app: "accesscontrol-java"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "accesscontrol"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "accesscontrol_schema_v3"
    image:
      repository: "accesscontrol-java-db"
    env: |
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
        - name: "FLYWAY_USER"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-password
        - name: JAVA_ENABLE_DEBUG
          value: "TRUE"
        - name: "FLYWAY_LOCATIONS"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: flyway-locations
        - name: FLYWAY_SCHEMAS
          value: public
        - name: FLYWAY_DEFAULT_SCHEMA
          value: public

# Container Configs
image:
  repository: "accesscontrol-java"
replicas: 1
appType: "java"
healthChecks:
  enabled: false # Disabled as requested
  livenessProbePath: "/health"
  readinessProbePath: "/health"
# Resource configuration for Go service
resources: |
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1.5Gi"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /access
  - name: DB_HOST
    value: postgresql-lts.egov
  - name: DB_PORT
    value: "5432"
  - name: DB_SSL_MODE
    value: disable
  - name: DB_NAME
    value: postgres
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: db
  - name: LOG_LEVEL
    value: DEBUG
