loki:
  limits_config:
    retention_period: 168h
    reject_old_samples_max_age: 720h
  compactor:
    compaction_interval: 10m
  schemaConfig:
    configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
      - from: "2026-05-21"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: tsdb_index_
          period: 24h

singleBinary:
  persistence:
    enabled: true
    size: 50Gi
    storageClass: default
