variable "region" {}
variable "environment" {}
variable "vpc_name" {}
variable "public_subnet_name" {}
variable "public_subnet_cidr" {}
variable "private_subnet_name" {}
variable "private_subnet_cidr" {}
variable "project_id" {}
variable "force_peering_cleanup" {}