labels:
  app: "care-frontend"
  group: "care"

namespace: care

ingress:
  enabled: false

image:
  repository: ghcr.io/care-ecosystem/care_fe
  tag: dev-30-bf1ee72
  pullPolicy: Always

replicas: 1
httpPort: 80
appType: ""

healthChecks:
  enabled: true
  livenessProbePath: "/"
  readinessProbePath: "/"
  livenessProbe: |
    httpGet:
      path: "/"
      port: 80
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readinessProbe: |
    httpGet:
      path: "/"
      port: 80
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3

resources: |
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

initContainers:
  dbMigration:
    enabled: false
  gitSync:
    enabled: false
