FROM blacklabelops/logrotate:3.10.0-r0

MAINTAINER Senthil<senthil.kalimuthu@tarento.com>

# This repository is fork from blacklabelops/logrotate
# This docker takes following environment variables
#
#
#   ENV LOGROTATE_OLDDIR=
#   LOGROTATE_COMPRESSION=
#   LOGROTATE_INTERVAL=
#   LOGROTATE_COPIES=
#   LOGROTATE_SIZE=
#   LOGS_DIRECTORIES=
#   LOG_FILE_ENDINGS=
#   LOGROTATE_LOGFILE=
#   LOGROTATE_CRONSCHEDULE=
#   LOGROTATE_PARAMETERS=
#   LOGROTATE_STATUSFILE=
#   LOG_FILE=

# Github: https://github.com/blacklabelops/logrotate
