namespace: care

image:
  repository: ghcr.io/care-ecosystem/care-celery
  tag: dev-80-0c34706
  pullPolicy: IfNotPresent

replicas: 1

imagePullSecrets:
  - name: docker-registry-secret

resources: |
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "750m"
    memory: "1Gi"

# Configurable values — override per environment
postgresDb: "care"
redisUrl: "redis://redis.backbone:6379"
celeryBrokerUrl: "redis://redis.backbone:6379/0"
bucketEndpoint: "http://minio.backbone:9000"
bucketExternalEndpoint: "https://minio-uat.digit.org"
corsAllowedOrigins: '["https://unified-dev.digit.org"]'
csrfTrustedOrigins: '["https://unified-dev.digit.org"]'
