apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ws.name }}
  namespace: {{ include "novu.namespace" . }}
  labels:
{{- toYaml .Values.ws.labels | nindent 4 }}
spec:
  type: {{ .Values.ws.service.type }}
  ports:
    - name: http
      port: {{ .Values.ws.service.port }}
      targetPort: {{ .Values.ws.port }}
  selector:
{{- toYaml .Values.ws.labels | nindent 4 }}
