apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: studio-project
  namespace: argocd
spec:
  description: studio services for the Azure AKS unified-dev environment
  sourceRepos:
    - https://github.com/egovernments/DIGIT-DevOps.git

  destinations:
    - namespace: 'studio'
      server: https://kubernetes.default.svc
