{{- with index .Values "cluster-configs" "configmaps" "radiology-config" }}
{{- if .data }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index $.Values "cluster-configs" "configmaps" "radiology-config" "name" | default "radiology-config" }}
  namespace: {{ $ns }}
  labels:
    app: care-radiology
data:
{{- range $key, $value := index $.Values "cluster-configs" "configmaps" "radiology-config" "data" }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
