cluster-configs:
    secrets:
        #ENC[AES256_GCM,data:9SOUeGViKDEBOtC7K8K3Z1YNr4IaP22jkV2ei2vr6o2O9ICZQZRMjIwSNL7bSCoQ1UdjDOMYASJTSmUBTeRrzuN77+XmPn+D0Mq3/quKZRrb9VDva7PUnGY89At6T1wWW9TmFK/FDIokjjvR3/FIV2Aqm2moquhFYhDYioO01MnvqCu36XGlqxvtP+EYKnLsm2tgPvng9SQ9PBdldcPIYzTOuyNyP32PjkMR14j72/Z7WHtgh4Eg3BWDtHKP+aG3TghmjkHtls9Zlw8zUdbjiUf2gUkpCMw=,iv:PV/qfeEVpnE+HBbK6+W45apWQmsNKl34Nyi7ElkZPrY=,tag:ufzoQNP6d1x1J9AFGk4jzw==,type:comment]
        #ENC[AES256_GCM,data:V8760bxf69QQ3Il/l+zoTm2qIs6p26A52xHxQ+9YJFHgSij9/baAtw0tcdxcyS++fCQr/eRbSRsrRHuv9XeCUi5hOG2D17HyyuI/i0SMSuvnxJXl4GeiHLQWXzFJYFV3rO7vEPZQZ/981sj5OV2x9YPuQfCNdna8zvGhrG8vLrcA0d8EHEZZDDswpQoBc3m33BAKtK4/dXLFtLoeTr8Fp1o/OHNLOLY+ngW5VkLJGc+SYkmZjZgpiJ4HkmvGheevwbbGx4bjs3SScdP9HuH24U+6A7IxzaVXPvzb,iv:KsTspvnM5wLQSvcpUr43nY8HhhxfdoLCve5L1HZLI70=,tag:58q+CmJ3KpfeH0egjQGRmg==,type:comment]
        db:
            username: ENC[AES256_GCM,data:sMw9jSfV+Lw=,iv:rMNQxgHpUraJCKuM7Urhe2nTBQfV5wUM5t2tKHg6ljA=,tag:8ddrWMa+ozwk8HjUQmSpTQ==,type:str]
            password: ENC[AES256_GCM,data:vLzo7fSZNmk=,iv:KFrQoHHcHdvDNKtHQvwPD2L4ibbF9GwAtSVaEIqpxhI=,tag:JBefOMxWc90cTMvb8P7h3Q==,type:str]
            flywayUsername: ENC[AES256_GCM,data:0JEd61/3hYA=,iv:4O/IslU4S69rKkgwXTPAezIjdMDuLe9hJ3b0luLDlkg=,tag:sL0HOb7Pn7ygV7MIRzlcfA==,type:str]
            flywayPassword: ENC[AES256_GCM,data:+7yqUQmLohk=,iv:LR33QuOo2TCiqDh5CJnyUoHe5swbvlGvT0Y3DEx3PAk=,tag:ngPnIU56iUBPnW38MNl4/Q==,type:str]
        minio:
            accesskey: ENC[AES256_GCM,data:uuM3OAw=,iv:hgOOrq06UybnesXwskLw4n0CFmXx4Uv+L7Ne/Mu/9wI=,tag:8rmXsYAFzojHpuEUzMjQVg==,type:str]
            secretkey: ENC[AES256_GCM,data:8KZx9XDr9jGY6yW6,iv:KSen1MgAYGXQ5JmyS+cT/xGkKWQdFB98aVTX2+QEGJY=,tag:oh/ZUejtiQb3JzZpyBJvkA==,type:str]
        kc-db:
            username: ENC[AES256_GCM,data:Cx+g7FJAIM8=,iv:bykgDPuFr9JCpFaevridBgStLDN+IgJaVp1Kr8Mh7vE=,tag:xBq0yHNrooRMtLEpvV05dg==,type:str]
            password: ENC[AES256_GCM,data:/9vloLt2kXQ=,iv:T7WCBitaLljwZIoGVnr/OLNw/Iv9z+wvXCV6BnG1fSI=,tag:SqnPPTiTAZB3TQ2ZDO4+ig==,type:str]
        kc-admin:
            username: ENC[AES256_GCM,data:gaGR7uM=,iv:r51bEvng3HYACXNsYi0s4ARfGOQA7RQP40hCSP8MTEs=,tag:rba3o87+eJIUtc/Ssu8Gjw==,type:str]
            password: ENC[AES256_GCM,data:I/nsT2Q=,iv:yNBweZFOeVNO/9zcVkN3k8OMZb7I+5/1jvBmTd9zxrQ=,tag:Xs1LUVdpkDmjhvDyTUnuyg==,type:str]
        citizen-broker-secret:
            citizen-broker-client-secret: ENC[AES256_GCM,data:UtrgOgXqM4axT2444FpbuWu7DHW80w4L2axhmA==,iv:SSYy/qU8gWMf0sF06Kx6RB1VoEqkaKKiAsU8n+YFsHs=,tag:0Lioh7fiwm/2P+hrgc5LLA==,type:str]
        employee-iam-secret:
            employee-iam-client-secret: ENC[AES256_GCM,data:T68vnYq0rWGjJqn+GeJgD4YjsuHPEsXDbVs=,iv:uhLUCjW9qEgNRzHyEVTYXIZAqQEWa+nwObS3SYqe2iY=,tag:GMDcIybKJTQKdK3F1Jy7Zg==,type:str]
        hmac-secret:
            hmac-secret: ENC[AES256_GCM,data:IuFWP03ChAyuEC0=,iv:2+E7sD9ujPPqCHZdKzOSXCpP9QdhCsbnHfxHOJPlI9A=,tag:Daecq+WLYiZ2/DEprBSkXw==,type:str]
        #ENC[AES256_GCM,data:LH5/J4EnYAf/m4d8HR25B3/UBOlUeBWzo7mOxJivLzwO/Df7KADymrkcGyAAEao0/75jMHS7UbNnWles9jOb6zO/nJaaHH2jMTBGSSZZFo1zddsOf1ihMrwDvY4eAszthVT8fIgoN6wV5BcJWq0eWSOsYQfgN2EHARr8ucB/MdhW6FZW5UxgGGE4NnD4SBE/m5m5WhzeLDRHXFnCUlXVnPSbjLFDKWW1ulmIkyia6JqRu0S58qvCk50gjOveh7kH12ys,iv:TBVgvlnCHMvwFLxkjDMm5gFczMgV9prST2WKLwGnpzU=,tag:eEDgb5L2w18htN/iZ1b7dQ==,type:comment]
        #ENC[AES256_GCM,data:kA/wdUyILAp3GcqDdEXqtREMcfc5g3pk406dUMaImvlrggbGzBPtGO9yfHMKjEjZnsTzwBhGlIfROGz9+scZxFMGOxYVyI3ms1dfHSTCROqH2JBqRcOiYX+lLo5ccscbr8qn4QWbOI+1FEwQYKqTM1K3plstA360UwXWVz+torYf01VQw4puE9lWYKkImvJtEUyShkE7OFlu5sTMcOjQ6gOfAEa65xrqPkNPL+g4ugP2/U1QkTg+Tw1tFpW/G8xA2Nr7UxNO2abvw2FxPH2p+GSoTg==,iv:eQ2tNxSZi7h3p0dPHUFJL2bLJyYkDPAEUYtL+SqM6wg=,tag:LdF35Dl7Iml/tXpscy7AIA==,type:comment]
        vault-approle:
            role-id: ENC[AES256_GCM,data:MfF422I=,iv:ByQVKIJIeoSP1eBEHhqU5VBFwZnlELfoiaLoI4SXla0=,tag:k3uPDcQ64+cjsLwGLr0B2Q==,type:str]
            secret-id: ENC[AES256_GCM,data:HuM8Ptk=,iv:Luq4D5rUjfv09b8YeihXP5WMubbiDKkebX2DUBcNyVs=,tag:rwcoXUgQVxfwQG5VziG24w==,type:str]
        #ENC[AES256_GCM,data:zrExwz0IBvBN1BWC5UH8lD92H35/iZ90xuRnKMn7AgC+EIYntHRRLFWfvG4eU1Ob3PCkBolVDWELI+E/CRIiOCOJrpdGCNcm4CNdjHghUrXzKv0g/IUrU989Szr1hS9wsUSs9X0UUMrQ9tEu4VHSVzWPPlG4qu4NXuuwv0UcAf5ykSrfV8QN+7Zo75c9/mFJ3VFWXGJVhUmwNBcz//hXVrkJCV9rDbifkAERjBoynnauZpPm+QQqjRt6FADKiskHAZf4iKqKshXsFKHqDNDP,iv:d5liiL4puxt+I+fYTCx6DrOs+zz37cJ0LpcIUpvO+iA=,tag:5mHubEnhmbWhjbhq4T0XAw==,type:comment]
        egov-pg-service:
            stripe-secret-key: ENC[AES256_GCM,data:mAOEWjStAfo2hQSDlBTRFgQevO0jgAbV9s186CDS0hD2wDX7j8kXxVLObZZM/clqFbnU3VEIh0pCkkWnXIB5YVQq4f+GTOlPir8VdW3sqx3wg5svXpeYgrKO6ZQXhDHQCRJOGOUD9ZOO+eE=,iv:rpaVK42r+JKpxIphKIdIDqQJ0R31DbHwnYgvEcbkfxo=,tag:1vwM5/HZOdA5D+L/PvD/pw==,type:str]
        egov-notification-mail:
            mailsenderusername: ENC[AES256_GCM,data:P6SM49gFLnWyhqr2BZXzp6aVTwk/tS0ZmOtbsQ==,iv:FqKd2eI2dVHAeesixt4aFIbO3qAXmSBejVBVY79xeH0=,tag:zfns32F9ItU8byUXQnWFAw==,type:str]
            mailsenderpassword: ENC[AES256_GCM,data:UamSXfrEHdUdgAaDYKriHg==,iv:u92REKHezOIG+EDmwR5h9zSoSFbEi1zfLCJy4AgUvkA=,tag:s9yrYwLd/CVOco2II2ppcw==,type:str]
        egov-notification-sms:
            username: ENC[AES256_GCM,data:4bUUY+TH8Q==,iv:8sVrsoQ+yGbWoDODMgbhmFMwRcp1y1ugvwh28+yeaRw=,tag:MyINb15NDBFjNvvzVYLVpQ==,type:str]
            password: ENC[AES256_GCM,data:Wdw+/AZ8v8o=,iv:WbW9QqFlKUxTz0z3rWHtpiGC803AYIN4b4dkv886TKk=,tag:WqLUv8frSH3iQqh3FyoADw==,type:str]
        kafka-kraft:
            kraft-cluster-id: ENC[AES256_GCM,data:0L0LzJitV4AI8EX3XdHteDQLvWz92g==,iv:YJ1o5mBwfGmk/xBMo9qk1IzTV3HTESIQppvErtc38rU=,tag:BbuZ/JYwjcLezLwoO2xHIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3BjQkczK2FOMEhkcE5j
            NzFxN2JLQzdUV3JXRzFjRW9XTkU2OGlwTnlvCjgxSEJYRmR6MjZIVUhBL3VkTENp
            Z0gxMFp6TGZ1dGs1NGtXQmtlWkJzUVUKLS0tIG5YK0Jub0Uva3ovaWE3VkxXWTQ3
            c3N6WXptRWZmU05WTEpnbHNyNlU0bkUKQ7Ms2mZmTxxqWTPtxwAhlFFuRMtv+bG1
            0pfB5XDicy5JvikhqZlBLCuUd0Nwa5KlMkLB0+mfQYJ6IzyMBv4dfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p4gn00rvm6psjwh686r9wyn6rsk5jgudz23dxhkltdswvzcdt3esamxke0
    lastmodified: "2026-09-07T10:05:29Z"
    mac: ENC[AES256_GCM,data:zWO1Xc8IsBMKVpfkKw1fIitA4LFug1BN3WosOQU48/qwMMp6OXNTMIWUYeh9kqllt1TzF76wXhyjcG+AHFYV1dEYQ2pdFr1B0Jhf2RLe4NDa8J+rLCxEZ0yS1YKHlLVSxLdcEWfHYlK5h7wnUvLXyQs2V3oRaEox9UPbxmzMkfo=,iv:QS9DlOxk1tRU3aZwmK8RKLkoFwal0NHiZ8HmgpQ8tXs=,tag:9Piv3yO7wBvIj3cQFCirzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
