cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:sMw9jSfV+Lw=,iv:rMNQxgHpUraJCKuM7Urhe2nTBQfV5wUM5t2tKHg6ljA=,tag:8ddrWMa+ozwk8HjUQmSpTQ==,type:str]
            password: ENC[AES256_GCM,data:vLzo7fSZNmk=,iv:KFrQoHHcHdvDNKtHQvwPD2L4ibbF9GwAtSVaEIqpxhI=,tag:JBefOMxWc90cTMvb8P7h3Q==,type:str]
            flywayUsername: ENC[AES256_GCM,data:0JEd61/3hYA=,iv:4O/IslU4S69rKkgwXTPAezIjdMDuLe9hJ3b0luLDlkg=,tag:sL0HOb7Pn7ygV7MIRzlcfA==,type:str]
            flywayPassword: ENC[AES256_GCM,data:+7yqUQmLohk=,iv:LR33QuOo2TCiqDh5CJnyUoHe5swbvlGvT0Y3DEx3PAk=,tag:ngPnIU56iUBPnW38MNl4/Q==,type:str]
        minio:
            accesskey: ENC[AES256_GCM,data:uuM3OAw=,iv:hgOOrq06UybnesXwskLw4n0CFmXx4Uv+L7Ne/Mu/9wI=,tag:8rmXsYAFzojHpuEUzMjQVg==,type:str]
            secretkey: ENC[AES256_GCM,data:8KZx9XDr9jGY6yW6,iv:KSen1MgAYGXQ5JmyS+cT/xGkKWQdFB98aVTX2+QEGJY=,tag:oh/ZUejtiQb3JzZpyBJvkA==,type:str]
        kc-db:
            username: ENC[AES256_GCM,data:Cx+g7FJAIM8=,iv:bykgDPuFr9JCpFaevridBgStLDN+IgJaVp1Kr8Mh7vE=,tag:xBq0yHNrooRMtLEpvV05dg==,type:str]
            password: ENC[AES256_GCM,data:/9vloLt2kXQ=,iv:T7WCBitaLljwZIoGVnr/OLNw/Iv9z+wvXCV6BnG1fSI=,tag:SqnPPTiTAZB3TQ2ZDO4+ig==,type:str]
        kc-admin:
            username: ENC[AES256_GCM,data:gaGR7uM=,iv:r51bEvng3HYACXNsYi0s4ARfGOQA7RQP40hCSP8MTEs=,tag:rba3o87+eJIUtc/Ssu8Gjw==,type:str]
            password: ENC[AES256_GCM,data:I/nsT2Q=,iv:yNBweZFOeVNO/9zcVkN3k8OMZb7I+5/1jvBmTd9zxrQ=,tag:Xs1LUVdpkDmjhvDyTUnuyg==,type:str]
        citizen-broker-secret:
            citizen-broker-client-secret: ENC[AES256_GCM,data:UtrgOgXqM4axT2444FpbuWu7DHW80w4L2axhmA==,iv:SSYy/qU8gWMf0sF06Kx6RB1VoEqkaKKiAsU8n+YFsHs=,tag:0Lioh7fiwm/2P+hrgc5LLA==,type:str]
        employee-iam-secret:
            employee-iam-client-secret: ENC[AES256_GCM,data:T68vnYq0rWGjJqn+GeJgD4YjsuHPEsXDbVs=,iv:uhLUCjW9qEgNRzHyEVTYXIZAqQEWa+nwObS3SYqe2iY=,tag:GMDcIybKJTQKdK3F1Jy7Zg==,type:str]
        hmac-secret:
            hmac-secret: ENC[AES256_GCM,data:IuFWP03ChAyuEC0=,iv:2+E7sD9ujPPqCHZdKzOSXCpP9QdhCsbnHfxHOJPlI9A=,tag:Daecq+WLYiZ2/DEprBSkXw==,type:str]
        vault-approle:
            role-id: ENC[AES256_GCM,data:Ln4bJhTAUouI9HZvKUShwBh6jVwK/4mZLna4ahbCLIWu7u8N,iv:OYQhZHNtXtX0DplKzcB2votc6X5nOid48XmT3PDbJiE=,tag:sW7BzqewesfevyqQ1MLVdQ==,type:str]
            secret-id: ENC[AES256_GCM,data:u0eySURPvBAWaDdqLBvpdfgv3s9GbssHzIxBg5KlqyUI7hhD,iv:rkpOZ5icx0jO5afgVPDF/z/ESCkR3HaXMQRgoMAoEto=,tag:piJzmujBiNl0PMNZKhzX8w==,type:str]
        egov-pg-service:
            stripe-secret-key: ENC[AES256_GCM,data:mAOEWjStAfo2hQSDlBTRFgQevO0jgAbV9s186CDS0hD2wDX7j8kXxVLObZZM/clqFbnU3VEIh0pCkkWnXIB5YVQq4f+GTOlPir8VdW3sqx3wg5svXpeYgrKO6ZQXhDHQCRJOGOUD9ZOO+eE=,iv:rpaVK42r+JKpxIphKIdIDqQJ0R31DbHwnYgvEcbkfxo=,tag:1vwM5/HZOdA5D+L/PvD/pw==,type:str]
        egov-notification-mail:
            mailsenderusername: ENC[AES256_GCM,data:P6SM49gFLnWyhqr2BZXzp6aVTwk/tS0ZmOtbsQ==,iv:FqKd2eI2dVHAeesixt4aFIbO3qAXmSBejVBVY79xeH0=,tag:zfns32F9ItU8byUXQnWFAw==,type:str]
            mailsenderpassword: ENC[AES256_GCM,data:UamSXfrEHdUdgAaDYKriHg==,iv:u92REKHezOIG+EDmwR5h9zSoSFbEi1zfLCJy4AgUvkA=,tag:s9yrYwLd/CVOco2II2ppcw==,type:str]
        egov-notification-sms:
            username: ENC[AES256_GCM,data:4bUUY+TH8Q==,iv:8sVrsoQ+yGbWoDODMgbhmFMwRcp1y1ugvwh28+yeaRw=,tag:MyINb15NDBFjNvvzVYLVpQ==,type:str]
            password: ENC[AES256_GCM,data:Wdw+/AZ8v8o=,iv:WbW9QqFlKUxTz0z3rWHtpiGC803AYIN4b4dkv886TKk=,tag:WqLUv8frSH3iQqh3FyoADw==,type:str]
        kafka-kraft:
            kraft-cluster-id: ENC[AES256_GCM,data:0L0LzJitV4AI8EX3XdHteDQLvWz92g==,iv:YJ1o5mBwfGmk/xBMo9qk1IzTV3HTESIQppvErtc38rU=,tag:BbuZ/JYwjcLezLwoO2xHIA==,type:str]
vault-operator:
    unseal-key: ENC[AES256_GCM,data:hysCVngeAx6Pfayx8M3uvFDLk+xDg1Mo+CnebPjkbbTeV59UThrJY/5zv1k=,iv:x2BSEPp5hw7+tNZs+Y9YIPkmfZC1DdIFjNzVmcHsnSI=,tag:VPPU+fWw5bi59CQsW3Njzw==,type:str]
    root-token: ENC[AES256_GCM,data:JVyRrBRaObTmN/a8XjoLZVAsWJpnWAhCiiPNQg==,iv:nJsbPIsp3wKXS73S2uPqBzpMUpybJg+4KsdQavB8ufE=,tag:Y7+2Kb+WCU1sPnBhwQhBYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid3BjQkczK2FOMEhkcE5j
            NzFxN2JLQzdUV3JXRzFjRW9XTkU2OGlwTnlvCjgxSEJYRmR6MjZIVUhBL3VkTENp
            Z0gxMFp6TGZ1dGs1NGtXQmtlWkJzUVUKLS0tIG5YK0Jub0Uva3ovaWE3VkxXWTQ3
            c3N6WXptRWZmU05WTEpnbHNyNlU0bkUKQ7Ms2mZmTxxqWTPtxwAhlFFuRMtv+bG1
            0pfB5XDicy5JvikhqZlBLCuUd0Nwa5KlMkLB0+mfQYJ6IzyMBv4dfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p4gn00rvm6psjwh686r9wyn6rsk5jgudz23dxhkltdswvzcdt3esamxke0
    lastmodified: "2026-09-17T10:54:48Z"
    mac: ENC[AES256_GCM,data:3K/8zvwRWHEri5ReOvsT4w8HoVH6lxMWPzcXZ4PvOTUoAUDMNJzJ3OB7geSDC4sBktvrPZyJ4IKYX2NpBN7UCP70sOk96PpJWgS00QaqsrXKkTdEyjPB+Aa1LCnDWUrxgKHwIsBeTgtpAWyRlhgtkOnlggB5Fhqd2S0cAY650ko=,iv:pXffUTssaNHSV7doDwrgXSzjzdyhFNSzMStJKvqdcd0=,tag:/7OqJGOmjtKV8e/ONfFRZw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
