cluster-configs:
    secrets:
        #ENC[AES256_GCM,data:NOglkZEVjUnEjz31qXPCPZ6nNariHibBD/6ADDs/adC6a0HX9Qqh+2QPnd1M4iE58nPdzMJOBqgV927Dq1Q4obFsPUf0s8Ccsbw4qjE=,iv:QIvpLaEae7kayHw3KsldMw2fVidplvsDpayiLWLYEJk=,tag:bc+5jomPERfVWq3x9sa1ug==,type:comment]
        #ENC[AES256_GCM,data:U5jUByKdtfIxW9PwAorcBBffJsYYKPEHl078PxYDd4QLChO3u/73ezAhF8W3XVrQU/1l9+JKDilvc8zPWYIRwBWus7+36vAIbIlWGDO8oQ==,iv:+NheYs6m71TeC/Z0F+YREqg2OvY/UBUrMsaH/CAk1vE=,tag:nDq/lRjsHxpa7jW7RSWWfA==,type:comment]
        db:
            username: ENC[AES256_GCM,data:sD3gftuNWSU=,iv:bovC+JMyo55UL4yIV6Sy1n44Y5UZqMbHapvP0XMkEC0=,tag:iu4Q8d31nwni+VLOCbrU9g==,type:str]
            password: ENC[AES256_GCM,data:bc+Rl00UQVhmZ7XuAZ8Ir52GX4qiYGI7,iv:tzShyh9ZYnzFG7M7pCVS30BAoDTqMcUERkoOFMTjlys=,tag:J9BIr//KLScyQ648gUxY1g==,type:str]
            flywayUsername: ENC[AES256_GCM,data:+5A7wXo1kgU=,iv:FjxFGLfuAkDH+pjcgGb0VWW4/qcuDRc34p1GFh7hu30=,tag:x4DRpFZDwPxIe/qxCaHqCA==,type:str]
            flywayPassword: ENC[AES256_GCM,data:NnYQNslGJ1aa9cyu/EC5QHmYu4IZsCYp,iv:sgY5opkyOm4Kd8oFzhkny34355cPEFjZHUoNXEKSIPM=,tag:B5fDlb/6+fvjDlsH+JbvFg==,type:str]
        minio:
            accesskey: ENC[AES256_GCM,data:76E8TA9/IeIzNQTR3Hb6jNxlSso=,iv:djJYCqSX/Uh6KKCMqqx0CoEdM7Zg3K1SFtZvVm36Z9c=,tag:bTJB5W9o1RLoz1Xt+qXjpg==,type:str]
            secretkey: ENC[AES256_GCM,data:C8L6OHm4s+aVG4gY0eGyedgBIE3pSTor26DnlFAKom65FeRPf4tJvQ==,iv:8i5yDHQ0BhgO6YHo+MJJlYen60UoqlG9xBxzbIb2+q4=,tag:v+2DPUjNQBVR9CeoHsdO2g==,type:str]
        kc-db:
            username: ENC[AES256_GCM,data:ARZZFYjipUQ=,iv:J5+9Fd8cKpXzuqedCkUdx0yexYFWZeaQC2Y76uALF6s=,tag:ruieSwY8m49qVG3znT578Q==,type:str]
            password: ENC[AES256_GCM,data:CbPjMTb4bjwkwfB+UqfUpSwP2u3VNiAG,iv:rRvfrtqcePXib3sds9J8rERgibLC66S78WH5H3YkxNI=,tag:q1XgNR3X773tV908q8mg7w==,type:str]
        kc-admin:
            username: ENC[AES256_GCM,data:SHPJUMw=,iv:C674h8uumWLWJxV5c9X2qGzF/01dGVN6l97O5wAMzPM=,tag:kwgj1sNCC2T7T7RnaRUiwQ==,type:str]
            password: ENC[AES256_GCM,data:lOMSR0PLY+aarDPlo7Nxd3eEykkWw3Hr,iv:dng73oUDdeAxG69cxGjzn2ouIEisC2GS3vCxzd8iEbQ=,tag:CeukIdlLy0kNnUa3z8fWeQ==,type:str]
        citizen-broker-secret:
            citizen-broker-client-secret: ENC[AES256_GCM,data:lc64hBZy08jloDkJKlQEzHowgt140aeJTVzz4Mjo+ZM=,iv:SsX7j+2ep4LtyUXFSEUG5kyyXac391C0Oejy7mzamls=,tag:dh02Geb/3Wo/qpQTXAHIFg==,type:str]
        employee-iam-secret:
            employee-iam-client-secret: ENC[AES256_GCM,data:GImvCMYRFSugtNEtFRRXx0w1xQrQOew2HNOcxdUoTSE=,iv:g8n0Jbl3xABaa4Hds01IPrzFl0HnVVqDIQesU2Q+8eA=,tag:QcZXvshT1nH5hYNgL7GbYA==,type:str]
        hmac-secret:
            hmac-secret: ENC[AES256_GCM,data:pV44yqVTD7/98kX/2hBWGlsZCCrtAw+o0N8kCCCSeEdD2sJbwQ1p/WLiZtQk1IT2,iv:kqqeNtge6veTBbl5UISXHZMQ/oW6FPs329KPH0DRcDk=,tag:LiJSnEltCzike7+/XJdjpQ==,type:str]
        #ENC[AES256_GCM,data:A69bWL8z2vWR+UVU2c3lqn5s6ZcPoeFSsE/30q+6OPn2EXUGy3xEcop6wCYay2CRjiDuXMYpnXpryhfVpEs=,iv:FDhwRAeEIUWXVKnI4uKPI6NwYCxDdxx2mVrBj7e3LWU=,tag:QlWH96gaeEUjiheNKO9kvg==,type:comment]
        #ENC[AES256_GCM,data:t9JDXraNOED6DDTJcuxWirodgNCPU/aFoDbrrdt/RVZSajEAJhtqszF4ZZ0SU02JKxC7H7JcLN+1sLtoE2EbT9ZsBNveSMNcdTHc,iv:l3XeTZ2M8KLN+om4m8nWLSC7gu1s7lIsU6nPvbz453I=,tag:wXldHtq8LNSomMqNThYHwA==,type:comment]
        vault-approle:
            role-id: ENC[AES256_GCM,data:GKECXUBBwE2HgOm26bQIBezJFcZTQ8A=,iv:DsO9C8xlyQ5KqYfqoL2TQTA2Txw8Z3jv7JAi6MQnxJo=,tag:bJlnVNFlrv1wWU96Z6oRbA==,type:str]
            secret-id: ENC[AES256_GCM,data:2k5tFGnoF6FEdDAWlbi+0xvvLp9WKF0=,iv:JkXRBCt5TLc8E19BeLyXL+hw5g/J6172QYjLda2mC38=,tag:QSyQVZ7gHHp05KWYFy3fLw==,type:str]
        #ENC[AES256_GCM,data:cbr8YFJL54r/H/wcKsKrdBVHmvJbKyPJPGpoFuBzztNnlw7JkF+Xzw3FR5hLiNFlDRv5wWGr8+PjPehtyUvQgrrjVqhDEdQ=,iv:W82/PHGkwyqcvimP8UnCt+Ec/f3mFxyQRE8AQp8fvQ0=,tag:TOpX/dg14Sn7p+txeWwEwg==,type:comment]
        egov-pg-service:
            stripe-secret-key: ENC[AES256_GCM,data:DzkvRUIJWp+11H9pZBe/WX5y/4RGVeSm4MvM4Tn/,iv:5uCS10CCypJm8q3P52hGrjN5R3OaKtxS1z/WhwatE0c=,tag:jYIS3KSHWip4it0Rx1KEKw==,type:str]
        egov-notification-mail:
            mailsenderusername: ENC[AES256_GCM,data:/W9FxNYfZ/yLIRKgMhdWcBXVo0RA6ePbVWosFg==,iv:X7zWnJGx8AQPNeyyeAKCo9b28d0Zw5D3Skn8cAUHrKs=,tag:YlfWWaFr1vojSseMEIfWAA==,type:str]
            mailsenderpassword: ENC[AES256_GCM,data:8JzAFZ/1ebmyWusrBKgxCukCGg/mNQB4,iv:P2huSD5h05hDHzveDisUViM1Dgssp+ynE8S/VCv3Hdo=,tag:NZziUpxTe6O/ogYHIyqqXA==,type:str]
        egov-notification-sms:
            username: ENC[AES256_GCM,data:he/Gnk9gryeChpY=,iv:lDwNhKD2WH5WhvIwHUsYVml+b1Uf0xCVrlOEeej5ApM=,tag:s9QUwkqigGvMdLqLcRtnag==,type:str]
            password: ENC[AES256_GCM,data:D9hFSUcNuwOy4U9WiesbOQhWX2o0+MM=,iv:VmSGZJe9pDSKSjEks89NVNryAb8PPARGK1q9BlKGPV8=,tag:7jgXAIPjtJxInCTOTyF2EA==,type:str]
        kafka-kraft:
            kraft-cluster-id: ENC[AES256_GCM,data:ZWHv2TH6j4SbpqzSMz7kg0mIuA5A8g==,iv:bPMfmPGgEkPfFu4yPQ0mhswu7+oB0EbHK+YKjZqduZg=,tag:0DDLdvBI1FB/v76amqwlYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age106lv6jfjz5mnnmde8pw330d0ehnkkp5da9060yqnv3xr2askk5ysc999lh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTVlzNDEweEhTck8zUGRi
            cDNGZGsvazZHL3A0WW8vR3BMbUdKRVM3cGlFCkNQTkNVdkNhZVpQRlhia2RaWlhZ
            TXg1TzdaK2dEKzdTeG0xVUhqLy9lSTQKLS0tIGN0K2hBWGdjdlJOLzhvMjRVMzBP
            Nnl1VU8vVm9Xak1iQjBOeVFVSEtaRVkKrE3Pu/Dg394ZF94+oDc+w/8+59pDWFFc
            9cUFxzoZS6lx3KI95LlK9NzG+2zoUwNEjyVA9GcwgruhJcovbCw6Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T08:19:20Z"
    mac: ENC[AES256_GCM,data:IDfXFHcpq2AyS0F68ln8DsT2cBD1+iYF0iPrvNUUFzxM+kJCCFg4sBpo3aV+WrgYTSmdqp5aKf5zMSF7idAtU2vG4j52AGwQqhNsnQcb+weClOj7f+FJI64tGAMy6g0EB7b9+OTWTdTYJm5aXKL9c02H/w/qsTHXaeuVdy1ZYQo=,iv:3cceftmfxIq9IgytiagP3RdDrQ9wf2FUjVTT4jX6YPw=,tag:ObBLC54jAAm9vCd4WVRqBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
