global:
  domain: "<domain_name>"   ## Add your Domain Name e.g. demo.digit.org
  setup: fullsetup

cluster-configs:
  namespaces:
    create: true
    values: [ backbone, cert-manager, egov, keycloak, logging, monitoring ]

  root-ingress:
    cert-issuer: letsencrypt-prod

  configmaps:
    egov-config:
      namespace: [ egov ]
      data:
        db-host: "postgres.egov"
        db-name: "<db_name>"                                               ## Add db name
        db-url: "jdbc:postgresql://postgres.egov:5432/<db_name>"          ## Update db_name
        domain: "<domain_name>"                                            ## Add your Domain Name
        egov-services-fqdn-name: "https://<domain_name>/"                 ## Add your Domain Name
        kafka-brokers: "kafka-kraft-kafka.backbone:9092"
        flyway-locations: "filesystem:/flyway/sql,filesystem:/flyway/seed"
        timezone: "Asia/Kolkata"
        spring-datasource-tomcat-initialSize: "1"
        spring-datasource-tomcat-max-active: "2"
        server-tomcat-max-threads: "10"
        server-tomcat-max-connections: "500"
        spring-jpa-show-sql: "false"
        tracer-errors-provideexceptionindetails: "true"

    egov-service-host:
      namespace: [ egov ]
      data:
        account: "http://account.egov:8080/"
        boundary: "http://boundary.egov:8080/"
        filestore: "http://filestore.egov:8080/"
        gateway-kong: "http://gateway-kong.egov:8080/"
        hrms: "http://hrms.egov:8080/"
        idgen: "http://idgen.egov:8080/"
        individual: "http://individual.egov:8080/"
        keycloak: "http://keycloak.keycloak:8080/"
        localization: "http://localization.egov:8080/"
        mdms-v2: "http://mdms-v2.egov:8080/"
        notification: "http://notification.egov:8080/"
        otp: "http://otp.egov:8080/"
        pdf: "http://pdf.egov:8080/"
        rbac: "http://rbac.egov:8080/"
        registry: "http://registry.egov:8080/"
        url-shortener: "http://url-shortener.egov:8080/"
        workflow: "http://workflow.egov:8080/"

# --- DIGIT 3 service config overrides ---

filestore:
  is-s3-enabled: "true"
  minio-enabled: "false"
  fixed-bucketname: "<your-s3-bucket-name>"   ## Add your S3 bucket name
  minio.url: "http://minio.backbone:9000/"
  aws.s3.url: "https://s3.amazonaws.com"

cert-manager:
  email: "<your-email>"   ## Add email for Let's Encrypt certificate notifications
