cluster-configs:
  secrets:
    db:
      username: <db_username>        ## alphanumeric only
      password: <db_password>
      flywayUsername: <db_username>
      flywayPassword: <db_password>

    egov-filestore:
      aws-key: <aws_access_key>
      aws-secret-key: <aws_secret_key>

    kafka-kraft:
      kraft-cluster-id: <22-char-alphanumeric-id>   ## generate: cat /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 22

    keycloak:
      kc-db-username: <db_username>      ## can be same as db.username above
      kc-db-password: <db_password>      ## can be same as db.password above
      kc-admin-username: admin
      kc-admin-password: <kc_admin_password>   ## choose a strong password for Keycloak admin UI
