cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:jiqTObqYJV3Y,iv:8/301Ddg9IksxDV3oysE4/T997QAoCZpHHTgIR380YI=,tag:/TMr8lbHrOOSLYplQ008Zw==,type:str]
            password: ENC[AES256_GCM,data:6cP4Plz1X7w+wxOq6Y9u,iv:ZvwBTpwXQVRmvvBMc2/5whx3KVe7E3W6PrURhB9HwVA=,tag:CtT0W6S1Y0lki/XLHeK2LA==,type:str]
            flywayUsername: ENC[AES256_GCM,data:lmkJxPL829DI,iv:PFDLDQaPVKSekc4Rzx3PHpbJyfLJrUsCJF4cy5Xok0Q=,tag:97fvTMh3026gJ47A61N7ew==,type:str]
            flywayPassword: ENC[AES256_GCM,data:9x/frwjPZB2kXwmWIkZR,iv:5KxraRsvsafIg6uqVTtwRi+ptHFX0WbqUbU5qHfcLTA=,tag:2VEpItAcErXrP+tFVAhCoA==,type:str]
        github-config:
            gitToken: ENC[AES256_GCM,data:0cfXFcl9klf5V77gWCn/wzqOAH6xM3SHNcp5Nl8oXM4RPkrjLqi9hA==,iv:wm60s9Bh0qfyg90S5WfZTnL/5uKcOhC7EqJqXnMeOdE=,tag:GjYr3CijF+8vr7qqD4zjSA==,type:str]
            gitOwner: ENC[AES256_GCM,data:xFt/bRfeRnGajhi7,iv:K6Oe6d+qKpXLHHYZpWfW2nO6x9SR5wvPSFC+u4RGS6M=,tag:nMyuWHU2wIKLaB/oPZZ8QQ==,type:str]
            kubeToken: ENC[AES256_GCM,data:sqAFrQ==,iv:DJpp2QQasVyk9RdC8eWtsW7COmyzMgRU0x88TmeqzZw=,tag:2vVwOUex5smTtXxEbC2CBw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2026-06-26T11:05:25Z"
          enc: AQICAHjoFpZ6nEPX/aX4OW5tQRH6UErDgBxkQ7+YnwcCty+SrwEGwcn6LgCTo8133fMItYWjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuSaLvjRL5aQpP6DYAgEQgDu3aN23SLVn2hHbsW3UX8lbe8DCV46/gJV7wUcCMK1fqfGUL0cqUE5FFZobGrwZCX20gjKTeAEAo293KQ==
          aws_profile: ""
    lastmodified: "2026-06-26T11:05:25Z"
    mac: ENC[AES256_GCM,data:a3BCisQOEG4nIGkcBWYXhmhsPVXOBOijH/AgjGvPPGp4yMfQ4dkf0mkZUOC9GG1tgqHnBpNtJaEgndHNaPkVWlXuxPfGmHXXtCAni6h0CvC5c0XkN8VePesSIaH7dJguAI89UgmL5jkNeIexUbQmLwN0yeuH0LIKtiW9cVyndxY=,iv:Wx+jWrZRcU8+I45+6c9Snlc4ZqQ98XXIa6f7Izg9GlE=,tag:qbePoD+Nt4XcWEVVtnkZ+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2