cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:aJ3gH2/xmu6nLQ==,iv:7xuKYORNDmAQTnJ72L2/oby8Kp5GixEx6mVGcKHmZmM=,tag:rHBoBKuKZMu1/Li3ogln9Q==,type:str]
            password: ENC[AES256_GCM,data:cs2zWI/CKDSJNXXOOg==,iv:9VIy64RmBafNB4J3ACSqu6+VCtlJWKCu8/WbaBtvSWE=,tag:M8eHi/AhxQoU7fGzvh2udg==,type:str]
            flywayUsername: ENC[AES256_GCM,data:V04t/imoRnFnmQ==,iv:9MyySZjJScgb9oMvaoL4FngCNPjIDeF4sRE5zaf5AZw=,tag:CC83T5TWTXSaECgIm+gxIw==,type:str]
            flywayPassword: ENC[AES256_GCM,data:Oic+A++gtbJc0Fp0sQ==,iv:otTc+v+zoG99e5c03WXp/0y6xSx/8Im5RYJuFeqF7Ds=,tag:Jh3IU3nVO2Uub1Ynd9NW+Q==,type:str]
        egov-filestore:
            aws-key: ENC[AES256_GCM,data:SETE5PNpcW0rCMHLlF3FurkTDe4=,iv:6V/5+YVLwZQKzmxiRE1P8U9nS7xSEt5a4efpkry3nOo=,tag:0btC3R1YSZaEe2p5QX0/mg==,type:str]
            aws-secret-key: ENC[AES256_GCM,data:JAkfr9+4T2fu3AUxHlTV5jp7G+GIL0wvD09H0Czxs8PNzfzO75QM0Q==,iv:FSoSg6aeGU/K57Ip9K/SOjSZkvOaQGg5Ztf1dnMtaH4=,tag:30Nl4f6bFVyV2lvYLpA7sg==,type:str]
        care:
            POSTGRES_USER: ENC[AES256_GCM,data:+7CQKdJmXivhJg==,iv:jGqf8nWH+iDOEqT1jknVR/YlvkofCSvHgORgaMYJPz4=,tag:ZS1q1kXOdDlVO+swJ4QTLg==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:JycLNdr7gen+QA==,iv:5Xm4cjO0wssJDhpG8j3FGOvZbKKG6kABxSfwyrvsrfk=,tag:XCEu8ZTEbyJyzcpBZp1qcw==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:aWZuiLremvABDNtb08POkiVen9X/simR5Ly8r/RyPMx5P6kFnY2rEnZWTSqsfWJ3pL5MjfdsBpjl2e8a9JUrHtMLBmNU0HYjWXr1lO1Uau9XMthA5GlLKfXV8nnNhuVeE0oYaLmW275A,iv:XDrAVnyxTWAFgXM8xQ08j1cD5W+SqLUYw/zOXJlW1GM=,tag:MeUG2idkZf5QxCy/9omEtQ==,type:str]
            SCRIBE_OPENAI_API_KEY: ENC[AES256_GCM,data:Q+XiCZBm12O7UR9bj5TqBfJLlier6Sxdkekjjw==,iv:ZYqh6eSGfGhP4h6zW9sXyhMC5EJHxJVYR6nCnTpN790=,tag:dfYhEPAoKXANbbS2f6ivqQ==,type:str]
            ABDM_CLIENT_ID: ENC[AES256_GCM,data:S3J1nPsYDrOBGiAThPXqxbAi,iv:Zp2nodOPWfQTJg8p1fYc6P3/Jpju47M1yPV4K30LIQk=,tag:skFXMhHOVn671/vQC6mwsA==,type:str]
            ABDM_CLIENT_SECRET: ENC[AES256_GCM,data:zAL04mY5wD4m/jdom0UskvZ5HLAuiF4=,iv:PVpkvjEVVTei3aIxtaXAknPl/T31ZPBGSQP1GycZJfU=,tag:uR3Cq7Bto36lUUojy38Oyg==,type:str]
            EAUSHADHI_API_SECRET_KEY: ENC[AES256_GCM,data:vAUxXFS/kHaDvcFvvsJ3WrtwfJgP2Etm,iv:HOv+q5GRGLR6YdHUdPaO6AXE5NDHm/VJoAaIEyLb5yc=,tag:BZG+aG7NODWgqVJqT9s17Q==,type:str]
            CARE_RADIOLOGY_WEBHOOK_SECRET: ENC[AES256_GCM,data:Iu637Mcv/O/a0Cs=,iv:vXu+3XverWj2qGpilq58chZ5y33bXJA0lVnTNRDpuY4=,tag:buZ8t9D6vLqs30v0HpHfpQ==,type:str]
            WEBHOOK_SECRET: ENC[AES256_GCM,data:ovhzRwnfOJ+zHMU=,iv:p8reTMYu+RAYZial+4qFmqhWTbsFGvzszNIsQpIXLMQ=,tag:9Z0Me0rUkScx080v93BhGw==,type:str]
        radiology-secrets:
            LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:r4b0DcApHEcGfg1oFGINRn0=,iv:iyjQCjVxUV/+GOXFtpQkWZQju2FDEUPfCEzq8yFVWbg=,tag:Pn6ywxdj9WkZOsXtvVVDWA==,type:str]
            LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:gxpI8iXf9MgP+uijEzZ2cUPQ1Q==,iv:uTUlrUGt2/6Hz1A5pGwaOZGjwr0vLzgg4hP6ffFn3q4=,tag:cc+/XShkeiMXlG/7gd3RRQ==,type:str]
            WILDFLY_ADMIN_USER: ENC[AES256_GCM,data:uTokDsQ=,iv:mAn4x+Bg0R31j8SRbV4F+hj/7reuYrVOfBUTtkHwfMI=,tag:UDfxNv+b68Jzp6kCGzCHUg==,type:str]
            WILDFLY_ADMIN_PASSWORD: ENC[AES256_GCM,data:aFfm3s4m++jg8lY=,iv:Pi7yh6Uj0Ab1HAHATSxVcq3On29fXQ8EY9LFIX607vc=,tag:doPJea/mRrIuBj9bgqNs7w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2026-06-29T08:43:27Z"
          enc: AQICAHjoFpZ6nEPX/aX4OW5tQRH6UErDgBxkQ7+YnwcCty+SrwFI8IpYc/yVscA5QxNjHKOdAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwV4xE5DWvUG55jsNAgEQgDveHGgcALLsGgWj2aQPmjZE3Du96YOaMlJQH4rk+2WLzTMJWOPew1koVUIISnpaW8OUOUjINsFdZaLcsA==
          aws_profile: ""
    lastmodified: "2026-06-29T08:43:28Z"
    mac: ENC[AES256_GCM,data:6acAjsj2g8rfIV0q5V4UyYzDKKbKXqj5steooNPk3Sm/kuVrBwZsgwmOHTEcnMWNjvE2vRlRUqunXgzSJF+jBpoibppFp7VdDMPbvAP+ISrAJpJNFSO5/uU1THGGZ8ALMLTwtMQO7TrWTlsCY+hjcqnW2Vjankiiht8n2W5Yfl4=,iv:KeUStruacgZaRhka9W72uNe9SyfukY5GJtGF6uUqm/s=,tag:uOZHIUXmDdnTvsYv+UtofQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
