cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:9WuC+xk7PYkbdw==,iv:Zp4T3zWnKR5mBdn9B1bGnmZzPtm8KKhabOp45seerro=,tag:+kN01yz/6voeNTbKUjNqhg==,type:str]
            password: ENC[AES256_GCM,data:8eFTZat4EiUKxO2xaw==,iv:q9vi7xzkzSDx1BPmPcRi8zZeHNF6eiOb5jVNYLG+jFU=,tag:TVdWaExsuXtcdTwgB2XFHg==,type:str]
            flywayUsername: ENC[AES256_GCM,data:6Q7K+J7h7teoWw==,iv:hDJhzDvLViFKngOwXoGCwnDWSNbSJTWAEFYOvxjsisY=,tag:dml1Acl4UdY09vUaol3jZw==,type:str]
            flywayPassword: ENC[AES256_GCM,data:bkV/cyXwfRq6H2CB3w==,iv:eEBnFkdEVWYbAEVypXBEmCkuPTDo0QizPmF2GkwjCEQ=,tag:tTooTZ9DSD4Rxd1X0/KbGA==,type:str]
        github-config:
            gitToken: ENC[AES256_GCM,data:GUfSzS70lPZHvRSsKjw9m1/F60IaYgUj750KZ8dAzQQgoBcwxwXkAA==,iv:otFY8PqHTNbb7oUFvUEkU6ZNMNhIeQs1WIQ9U8UDcwo=,tag:vZUJXxfpJ3B5syQkO3G3vg==,type:str]
            gitOwner: ENC[AES256_GCM,data:29uQGf9fJTqGTVXV,iv:RQKCedAQIeO+7ksaMlCYP1tfqLOwSxp30x61JcrBQOI=,tag:jmAvmSeUQJgHP+dTFcMuMA==,type:str]
            kubeToken: ENC[AES256_GCM,data:bOE2Rg==,iv:z+iX9jzaEvQheMxGWHBQRw7hcLu4+fIfo/3J1RZGwNY=,tag:9PtM1e4B+ASzkl5B7isAuQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2026-03-31T05:02:49Z"
          enc: AQICAHjoFpZ6nEPX/aX4OW5tQRH6UErDgBxkQ7+YnwcCty+SrwHycBAtZicqOWmlz3z+2oVqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4mgVUP+iarIWsigmAgEQgDuNoFcep7GpQ/nw88Us3opGYmrpOTb9g6xNhJ2l96KS8FW2zlIo0rdtg4bcAaw6OOqR3H+/YGQMnVEomA==
          aws_profile: ""
    lastmodified: "2026-03-31T07:42:58Z"
    mac: ENC[AES256_GCM,data:WVfIYezH4ghIP6cN1kM3f7LhifeD9KPtOBDJkhTyOrzVPJFnIK6xUGxzF0MxJ2+lQfX3HhQD3EwMW4ZMFB3Z4P7p+iQj0DxDbMRW5mgvCn5iB2oG4xe5D5wh1z55xGMGA2UnzB/xMdt+l5shn5GKi+QkrFgDnpOh7G/XZ8FBQpc=,iv:IxBeOI0sGWl/I4v11Q/LtnFmR4zPY1JMPosret2L7oc=,tag:2LfzpVd2mYVoTrsMM9+yrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
