cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:P7eJg7L6BHNkDw==,iv:V6c2oa4rgef4zVubyBVqfLzaBPqL37NkBHnS4ow3t4I=,tag:KPWWcyV2RRkz2dbEgIZvGw==,type:str]
            password: ENC[AES256_GCM,data:rwmZvpS1UFgLuqEM8Q==,iv:ZdKLKhW5BNC9cv7xWyES91V9527IhyxDZFtrG8/RMnc=,tag:AGKY4AtnM71vZwQvV0v7UA==,type:str]
            flywayUsername: ENC[AES256_GCM,data:SvFKmVr7KoATQw==,iv:lyzeqf80asZcscJbdEr3L/U8Ak8Xiwk0rA/n2tNDydQ=,tag:BV/qcv9YkdYejOk0nUYn2A==,type:str]
            flywayPassword: ENC[AES256_GCM,data:6yLOXN8nBhFymxYSGg==,iv:BOK2G6uctHpllOoHuOw4Ypf7lQ3RjSJCOsUXpLEanFs=,tag:tidMqqG0Xywp7jcIwxrtJw==,type:str]
        program-service:
            encryption-key: ENC[AES256_GCM,data:IiWzSeZ+h/I1bNAETaqkyswfeY23k5Ex4kuAqHDFRB3GtrTv55LS9s3g69JHnJiUu3tSidxm0iCQBPUr1YoFxios4bnZKTR7gJ3sxRBuILRVMD3Y,iv:yARWXhZBDlXrDuAV7249fQyrj6kfEBbgWICwrVI/aoc=,tag:gYzTSWJSpwjFmzAHK87qqw==,type:str]
            encryption-vector: ENC[AES256_GCM,data:FUQVNo4nbNWGd3GkdumFx4VAV49ZXdbMbt+aBNuOJyjx0DqPafIG3pBxrA==,iv:1LinJRf0lmr+7c3/bbs0DtdgQUFG9N515ATWV10ruF8=,tag:Cm/V4nKu/VDsRW3HQNo6KA==,type:str]
        git-sync:
            ssh: ENC[AES256_GCM,data:Id4wf1EOzvl+/4H+KHibViVrOK54OaesRa6F4grqTlj0TNH/Ji3h3q/cPvjjgZHsir/OBSkDgN78lsJbeav17LI/CR9hHd2k0AzR6DoXmjd0paB5noSC9XlRV3kCVD06rAXqu1aqz7CSSO4aZgHkHkru2nKeuEIawZL086swLEAtrvUCpyuUPbaImV2nruVs9YqFwPst7yDrUIAV/oWYdVidrm4L1yUprrrzA3ZAn4a5if/Xo7J/LpycEifVURocI+BXvxfMpOHAbut5LZl5DpeI7Df0oGsYGOXjz/UhlPljJfGNbBI5v4D3Q582ci47QfoGko3a1lqVtMebL4hc46iJ35iKbdHoibmDhTCysOGdquRPQloIYWqiRRSwPbkTQ9OGPpXzZT2zRxroeURpr0iNyfEtVAyamk3RthGGlK2B7u4OglImF7bklP7aXM3Gab7DfG/9ycgsgoyfRGg3ob8ET5lU+TUzrlIWFWlkhJu7EpuQmjzatfvu6TYosrV2Ik6nhw2zZ3FlV4h8iApf,iv:U6gNOf1ZJWePz2tRmZnqx11J7VxZG8auM2gF96hdryw=,tag:l+RDMvS/CSvN9RqY7IxCQg==,type:str]
            known-hosts: ENC[AES256_GCM,data:p3ew1QDJyoUfC0r3p/gp2zh1uR63e8aZhF+m0CMyFKZttHCjHl5N0YnZueyEJ4clQe00L51wgIOQ57VB4uB63LhBhwrgjTIF8SY9XWLwWzL55FH2r029S8TBMOMan6PwzoRlpj+CBghgoIZUlcSrMtJdEkuz1E0is6Z9OXx+u81mhfQp8fRQvTCEjVua1dPsD0K1TUZRTUrUen6Nke9T2g31KCePI9Fd5GPRWhKiXaayTGD46mYetpzLJLmg38Boin+dpz5beGDco6Xs905U3l+jITe0UeVFtC65AdJqltzsYKCwbA/DscQ5TPmH59RcyaJPNvl+Q46I/mI+aWDYYXp70TIuxsnMepqPuA8bO6X6YFJ34SumSH0BGtDVosNzD5nvEUfq+tZCKncyo4eVHQo/ubn8yw895xHDi5EbDbx8BWAzh1wnPGKUcmBZBmYz2KOji21GTQkhfjZnXMxrS8Bq+0aNCzZEqLQECCkL1P1D1Uka4VqiH+vXChOLSb8jgE72TXC+1UJe9bsm3XVSf9mryy4ALvAj3GJpw7nzlq60nQdE2KOoLpCEIJbIE/CcMhTmu5QuZGhilmFTSRG7YJfhG8bpkxTfcrURXO6ure5VlebeZqS57AS5+rRWIq/orXYlYJIxuVFQpPvwTmyCZelT4vwahyV18obNFimdOvmV7wsqu8w2CsbwDNLJ0kdNtlnDbI1xutpjWZa2MkkWjYqJQY6ujssgVgXHoYdiw2zhkcc=,iv:51O/Rc/gIHwY8UWyHJB8C1K+jZiEEaQugHroJa4MllQ=,tag:fOBLnlvvrMvRM27F0dTuUA==,type:str]
        elasticsearch-master-creds:
            password: ENC[AES256_GCM,data:E1hw4i2FK3KnvbbSip3khhuSIccWfl2+,iv:aDmQXY4ZRcwuN3JHR/5CetUQpd3O+NnudQ/qXUgno7I=,tag:M8XFKlEA2Ie9y/FZyxy8Aw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2020-11-10T06:48:05Z"
          enc: AQICAHjEvQaNWs0Zj/laHQzVyaV/OAacQ3AJGQojIvVJeuwcQgEkCaHUS5rBgOTSYF3KJCCLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpuUHqwmURtAwdOKHAgEQgDs7gNHFGN2+UnWe493tfMbEMio4ZKWliDRq37pf5abrPBri/ZJoCf5cPeN+zLXVqLWeBVxIjie+q5jusw==
          aws_profile: ""
    lastmodified: "2026-07-21T11:44:11Z"
    mac: ENC[AES256_GCM,data:DJO1zOcAwXfMcVmmv3HwIdy36t/KrWDM4KmRb3zWAuudj35M2z1Jn2qHF0YNkD2fvTe98uDOhLOvXF2cxeWPp3WKbgnKerUC7AFkdbBngP5dLRCopdNlLiqHy2mCxuQ7+NqIoUZIkzM4WYwSioc5Q9JeEtLZoYXcwiRFD3IYb8g=,iv:FUHZbkhrL/8yLzfvYQNrvfVExPqe3Znj3swqy1jmlqA=,tag:Gq2jsJn9jlnRZ5v9XtO7gg==,type:str]
    pgp:
        - created_at: "2020-11-10T06:48:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+gtFIQvidpKAQf/ZV/gS6UA3zPiDMT9Rjbg0nSVhDmsqR8ki0bWvzfVEDzv
            lXzcOnjuILj4TkTKc45Mq8rkyAiYMu1HbMXDnlK3NL2whq1v+OKEMrdWcdzpDhr/
            gu/E5uBX3+V9PwWWvpSUqBYKnl0iBz+MoUSx0kZnrRZ54lC/Rd9X/gRhN3pTqMn+
            Ihw6/6D6+7haqXtgAb2cdhVYG6O39RzKTO173AxK3fFYmzxXzSwBzJte0ZXapx8t
            PfY0aNyWTdD9OQ5RxRj53YBCGqDjnKuvFqTwTAaapJ4hO6mpVnFY6zl9vneX89HF
            5fL+eC3tMXIqyF8e6kVWvLuYMWz5QSf+4VAlyoB99NJeAU1WMfycVvvdEYbTHqqS
            ieWYJYkjC+TlwkmbZ/9XTleQdS6HwX3jzAcqCAdeK8hw7iGGAVXZYlG3iL0Yv05S
            q/xbgdrRuywkK+g80ybEf+MQSSPsd5Q8dO6TFhaQ4Q==
            =msen
            -----END PGP MESSAGE-----
          fp: B9FF61E01273EDF7DE298B52F4D6BD77E5C66196
    unencrypted_suffix: _unencrypted
    version: 3.8.0-rc.1
