cluster-configs:
    secrets:
        db:
            username: ENC[AES256_GCM,data:HW6WX6yd5r2M,iv:Al+ataUj4xQQMtbOsPDYpXwzHD7XdbRM2cOkdjB4Y4g=,tag:VsDBwEoyLMqyAg73fA4CNQ==,type:str]
            password: ENC[AES256_GCM,data:vcE4o0PvHw4QqmjqBLaH,iv:8VA0yXks+g3z33pmfXfLYSgkt7+nz0PJD8wC7lchBM8=,tag:YjjdS3GIGTFkLqrXk39S/g==,type:str]
            flywayUsername: ENC[AES256_GCM,data:ejf83GJMZE6m,iv:Vm4Jpq4RLTHhEjXAW5QhGgL97vQdSoPaBrAlQ5qQTHk=,tag:7UmfkA6uuHFH3LFgOD2D1g==,type:str]
            flywayPassword: ENC[AES256_GCM,data:VeM02E0xT/OsvF/hJnbH,iv:+arQJsMJU6WI9OsYy5luHo2zI/ZsCYn4QYwtHIW6YhU=,tag:7vYl9p29ICC0xQetZFuMNA==,type:str]
        program-service:
            encryption-key: ENC[AES256_GCM,data:rePzojk6CMljN5ynJ+KDDGOLG837mdcL13RASDt3JTcgGpUqqeRrc8nitVBmiOBINAG/+weyl8kg7BmUYKBxoDaFGT+RcCjy1VcapF3CIeSxpiaM,iv:T8GhegiMS8q0Fa8zzq7Bgv0Mj3rmE07gVNHWvaK20gE=,tag:Fdp2Ges4IiL/WuIy+bd+VA==,type:str]
            encryption-vector: ENC[AES256_GCM,data:1CNUbMpm2YDlgQxtvdVb2s3GSIIiXlvPOyni3wJVbEWDZrrI0CpjgaZJ4w==,iv:QVyo9zHL6MO6/JU7dfPIAq9DQ7sOm1WG1o7pXR+YH6A=,tag:0QXOzmb1DfyNLB5Dw1YoEA==,type:str]
        git-sync:
            ssh: ENC[AES256_GCM,data:x8W/s0wTa+B4jDC+iJ1JouwJMPIyiTlW7P1KM3AdA6yArwspg1IvBM8+JTMzCftEotWzW3cy/B3uhD6JSwuAnm7+6ocPeMY1L0GY7p2aC2uBWkDb0oIK/wD8YR+0IPCua2CgzYgADEhi5VxfFWYwdfUoWGxJ7QpyFxlWju5QFwLaEnbVOpvwL2g9Xenz2DV0BtqbWKyCY6Y8OnoQ/o0hzUtNeyjXgns0Ww8IjuiygfPL8FVxh/2+zAMRpWwGKyLs7P5y4HmimeJb/dUe/2KVCkh5CKLAL/4FJCA5Tbfz/ep8oKi8h0CLFia5qZkDpgxbu92tlZpkHYpaMVMbX5NB/QUs1pjUJ8Nr60at7Ipshb1xpXSZugN7tX/uOCmj5RukAMNAYYVM4F+ayOg8/vWl6on8a9kxqS9U55vt4T54v8qJ2W2M0rupy8XsmuqLWdByBUmPkBdPnItRQq+8EPGEIGrF2n4J+zdrfhj5FHW2ICAwUqsR7vQpTScg3j1hds8z2tjRYWO5/EhaF3ieA/l4,iv:btwJUVB+wViIarGWV4oIcLHad3Nt/dY+CkK39ko/Fmg=,tag:Q1IJhB0veV+lItat8CdENw==,type:str]
            known-hosts: ENC[AES256_GCM,data:Fpkvy+Uq3qrvfZJ1/c3v+M2jbFEfguTaPp5DcZzreFYtD5wg+KZqRGDIOtAvaibP09BFQWBXVvTvsN/nOzH5wwGgsNfbYHLyqppiZ3jjeq/AHZHkP97ryJPIxd30jLAl4xq61vXvPdBFJLWAZiQjQ/bEMlef+tXXcDIb9A4ITX+EehR/4m1ORdVqKxdjPDJFLeok/2znq2wsOHOqv+WikyXRBxtizQQt8TFIHZwuSkdJZ099IyX0ZPhuVen/HSR69FhnDBBezU0F7owRROaThOFUDnNZ7HNyajkdlkZgTX3qRaxH6M4JbcjJoQJjhg4SHmubkk/4tKdsxFdjHrPtGsXgl5P3Pf7tuzhKAhbApOeNmNtod7vnd8LaNFgT6eG8J3rO0VHxS4r9N2oK5vCNBBb8p/93jkSiCehPRA3aVAQcFns+MmpnMMObKGg2l7MvcwbxhQS43EwM6/LSfLUaRuq/gX35LWfT4FIMEL6bFdp7Rtyfaw3KaRn8dWn0Cs3cKmfCG/mZvRhixG3eilA1l2CT/0UM17gvc2EhU347jGyIok+cGxYtrmdy9TTzP8G7Xz4OKsn2yvLCMVwS9s4DwECnTN0TxfQhT/6ysJlpaVolm6u5jLqEV7AeDyzVOWgSUTZp7tbnQU4q4AiiRhz171JnjlHf/5qHVR/vmAEDlOAgrlrWQOn8vAxUtiNHx4m6gTkfzOGH1ccP5n6nS1HIPQONRPj2GLl1EPVUOVAv/JMTzzs=,iv:5WdOv8KuWTa+yH6AyUtgxmiV+m4I+HFvnLtcLaK6Y5E=,tag:+r5NcoRa2+VObWbeg8jqng==,type:str]
        elasticsearch-master-creds:
            password: ENC[AES256_GCM,data:o8SB8scYK8UWAvg1W/0z/3YEVp+mQgBv,iv:5C/tLwJ7OFHqg6GdXJtGCLyPJRKlt3OMbzEvZ1HpBm0=,tag:0jY76QkPglVoPqgNYbaf5A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2
          created_at: "2023-04-11T06:12:24Z"
          enc: AQICAHjEvQaNWs0Zj/laHQzVyaV/OAacQ3AJGQojIvVJeuwcQgEnl3vKuiulVvdACmIjrOerAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMygJAIKOE3FL3EJm9AgEQgDvGqHGCiX7vbFH+FBvVbRy5v+0Y/WI4g+4RBH2ySp1g+6AuwJIVTObmVdgAgvyQbtL41mzufy2QY7lqKA==
          aws_profile: ""
    lastmodified: "2026-07-21T11:44:09Z"
    mac: ENC[AES256_GCM,data:e82zXP5q2uPBlTamXH0KQ9VluCP/i6lSr22McWlORE6dnVi1j/ifiStoJ3OjBGAh3rTPbadfV0TPZZfkn+NcG6FIgpNtNQfByfixni0y6nbZtFjDS4leT6O/Oqbru4GQgp+zFoPUqkhxTVtTnQg4ZN80fO4Xzsq1OqvsqFBzhtM=,iv:DBZw/jiXarAfblCGAU8cfu13Xt7ZqqKkBInqoZ7K42o=,tag:mTI+p15f/6ND6LygNXSxMg==,type:str]
    pgp:
        - created_at: "2023-04-11T06:12:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA3QBUEHknBKFAQv8C7JFZHpg2efe9t2EYW0AtYoDfwGVu6sDD1v2MKwkYhe8
            L/H0bFb1fDavJRKIaZPhcR2LfeBisIUCCemDm55Rq6/0zpvQ4s22KH6Tr8qZwZfo
            HIrFA15vgCpnmcgRNXJ/ZPWbIwMRMbE+gZ7rMMXDcpoRjf/sFBFD9qD5ErQS8W87
            vbPhqOIK7sbDCGLU6FAUUuK9hXqHrF1hzE4T7bg8MhK8GNVLhs6eufouzKfPbnk5
            HIEqGdvC+5VLvhm+WgFgO027CVNCO7FQZ5Dqb1XVjRMY7P8XlSWEpw2WEdxay1yd
            7HI+ridZHUDly6enq32hOUN0iK8+QimtgFW8yBwilKE6PInVxId3lyDaq3JAjnxc
            kHuHnZp085wefjCXY0sIYo2POjukqo7oB4oghwXhTVXCLs6yoqNKf8Vjmmr+1zL8
            5O5sNWI0MTx9B0WauSjcXLUHhcDDYrMQsxjpqo3vLpa7+VRtNTMNZI9Zz+vITUCE
            igY8lsxMwwo5DM1VT5b51GgBCQIQ++dgAogwETbMwd0TvEjqQk7WmOEfNnYUvF+L
            MWk1voRbV6OLUScsVGRc1k7qrjGTvCrEs1JWLTV5y9aRPFIlhvq3rC2jYMwqyfW/
            LDoEZdFZE7tlZWUmuQMpbyjF3WEsXQn+JA==
            =NBp6
            -----END PGP MESSAGE-----
          fp: 58BE5C4525DFE047D960AFF29E8891E02D93FD9F
    unencrypted_suffix: _unencrypted
    version: 3.10.2
