# Common Labels
labels:
  app: "studio-calculator-service"
  group: "rainmaker"

namespace: egov
# Ingress Configs
ingress:
  enabled: true
  namespace: egov
  zuul: true
  context: "studio-calculator-service"

# Container Configs
image:
  repository: "studio-calculator-service"
replicas: "1"
memory_limits: "256Mi"
cpu_limits: "200m"
tracing-enabled: true

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: CONTEXT_PATH
    value: "/studio-calculator-service"
