variable "server_name" {}
variable "sku_cores" {}
variable "sku_tier" {}    
variable "location" {}
variable "resource_group" {}
variable "storage_mb" {}
variable "backup_retention_days" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "ssl_enforce" {}
variable "db_name" {}
variable "environment" {}
variable "db_version" {}