{{- $root := . }}
{{- range $cmName, $cm := index .Values "cluster-configs" "configmaps" }}
{{- range $ns := $cm.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  namespace: {{ $ns }}
data:
{{- range $key, $value := $cm.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
