{{- with index .Values "cluster-configs" "secrets" "keycloak" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kc-db
  namespace: keycloak
type: Opaque
data:
  username: {{ index . "kc-db-username" | b64enc | quote }}
  password: {{ index . "kc-db-password" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kc-admin
  namespace: keycloak
type: Opaque
data:
  username: {{ index . "kc-admin-username" | b64enc | quote }}
  password: {{ index . "kc-admin-password" | b64enc | quote }}
{{- end }}
