{{- with index .Values "cluster-configs" "secrets" "egov-filestore" }}
apiVersion: v1
kind: Secret
metadata:
  name: egov-filestore
  namespace: egov
type: Opaque
data:
  awskey: {{ index . "aws-key" | b64enc | quote }}
  awssecretkey: {{ index . "aws-secret-key" | b64enc | quote }}
{{- end }}
