# Default values for egov-finance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: backbone 

# Common Labels
labels:
  app: "valkey"

# Container Configs
image:
  repository: "valkey/valkey"
  pullPolicy: IfNotPresent
  tag: "8-alpine"
replicas: "1"
httpPort: 6379