apiVersion: v2
name: clickhouse-operator-helm
type: application
version: 0.0.1
appVersion: "latest"
kubeVersion: ">= 1.28.0-0"
description: |
  The ClickHouse Operator is a Kubernetes operator that automates the deployment, configuration, and management of ClickHouse clusters and ClickHouse Keeper clusters on Kubernetes.
  It provides declarative cluster management through custom resources, enabling users to easily create highly-available ClickHouse deployments.
keywords:
  - database
  - clickhouse
maintainers:
  - name: ClickHouse Team
    email: operator@clickhouse.com
home: https://github.com/ClickHouse/clickhouse-operator
icon: "https://clickhouse.com/docs/img/clickhouse-operator-logo.svg"
