server.servlet.context-path=/worker
server.port=8080
app.timezone=UTC

spring.main.allow-bean-definition-overriding=true

#------------------------------ REDIS CONFIG -----------------------------------#
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60
spring.cache.autoexpiry=true

#------------------------------ DATABASE CONFIG --------------------------------#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

#------------------------------ FLYWAY CONFIG ----------------------------------#
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.table=worker_registry_flyway_history
spring.flyway.baseline-on-migrate=true
spring.flyway.outOfOrder=true
spring.flyway.locations=classpath:/db/migration/main
spring.flyway.enabled=false

#------------------------------ KAFKA CONFIG -----------------------------------#
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.value-deserializer=org.egov.tracer.kafka.deserializer.HashMapDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=worker-registry
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.consumer.properties.spring.json.use.type.headers=false

kafka.consumer.config.auto_commit=true
kafka.consumer.config.auto_commit_interval=100
kafka.consumer.config.session_timeout=15000
kafka.consumer.config.auto_offset_reset=earliest
kafka.producer.config.retries_config=0
kafka.producer.config.batch_size_config=16384
kafka.producer.config.linger_ms_config=1
kafka.producer.config.buffer_memory_config=33554432

#------------------------------ KAFKA TOPICS -----------------------------------#
hcm.worker.consumer.bulk.update.topic=hcm-worker-consumer-bulk-update-topic

#------------------------------ IDGEN CONFIG -----------------------------------#
egov.idgen.host=http://localhost:8082/
egov.idgen.path=egov-idgen/id/_generate
egov.idgen.integration.enabled=true
egov.idgen.name.worker.id=worker.id


#------------------------------ ENCRYPTION CONFIG ------------------------------#
egov.enc.host=http://localhost:8083
egov.enc.encrypt.endpoint=/egov-enc-service/crypto/v1/_encrypt
egov.enc.decrypt.endpoint=/egov-enc-service/crypto/v1/_decrypt
state.level.tenant.id=ba

kafka.topic.audit=audit-logs
egov.mdms.host=http://localhost:8085/
egov.mdms.search.endpoint=mdms-v2/v1/_search

#------------------------------ CENTRAL INSTANCE MULTI TENANCY -----------------#
state.level.tenantid.length=1
state.schema.index.position.tenantid=0
is.environment.central.instance=false


#------------------------------ LOGGING ----------------------------------------#
logging.pattern.console=%clr(%X{CORRELATION_ID:-}) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}