# Common Labels
labels:
  app: "worker-registry"
  group: "health"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "worker"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "worker_registry"
    image:
      repository: "worker-registry-db"

# Container Configs
image:
  repository: "worker-registry"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/worker/health"
  readinessProbePath: "/worker/health"
appType: "java-spring"
tracing-enabled: true
kafka-mdc-enabled: "true"
central-instance-build: true
heap: "-Xmx256m -Xms256m"
memory_limits: 512Mi
cpu_limits: "300m"
memory_requests: "368Mi"
cpu_requests: "200m"
java-args: ""

# Additional Container Envs
env: |
  - name: TRACER_KAFKA_MDC_ENABLED
    value: {{ index .Values "kafka-mdc-enabled" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SERVER_CONTEXT_PATH
    value: /worker
  - name: SERVER_SERVLET_CONTEXT-PATH
    value: /worker
  - name: INDIVIDUAL_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual
  - name: INDIVIDUAL_VALIDATION_ENABLED
    value: "true"
  - name: INDIVIDUAL_SERVICE_SEARCH_URL
    value: "health-individual/v1/_search"
  - name: INDIVIDUAL_SERVICE_SEARCH_LIMIT
    value: "200"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_IDGEN_INTEGRATION_ENABLED
    value: "true"
  - name: EGOV_IDGEN_NAME_WORKER_ID
    value: "worker.id"
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: EGOV_ENC_ENCRYPT_ENDPOINT
    value: "/egov-enc-service/crypto/v1/_encrypt"
  - name: EGOV_ENC_DECRYPT_ENDPOINT
    value: "/egov-enc-service/crypto/v1/_decrypt"
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: KAFKA_TOPIC_AUDIT
    value: "audit-logs"
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: "egov-mdms-service/v1/_search"
  - name: STATE_LEVEL_TENANTID_LENGTH
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-level-tenantid-length
  - name: STATE_SCHEMA_INDEX_POSITION_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: state-schema-index-position-tenantid
  - name: SPRING_DATA_REDIS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: redis-host-worker
  - name: SPRING_DATA_REDIS_PORT
    value: "6379"
  - name: ATTENDANCE_LOG_KAFKA_FIRST_SIGNATURE_TOPIC
    value: {{ .Values.firstAttendanceTopic | default "first-attendance-log" }}
  - name: ATTENDANCE_KAFKA_TENANT_ID_PATTERN
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-tenant-id-pattern
