{{- if .Values.hyperdx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickstack-config
  namespace: {{ include "clickstack.namespace" . }}
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.hyperdx.config }}
  {{ $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
{{- end }}
