{{- if .Values.hyperdx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clickstack.hyperdx.fullname" . }}
  namespace: {{ include "clickstack.namespace" . }}
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
    app: {{ include "clickstack.fullname" . }}
    {{- if .Values.hyperdx.deployment.labels }}
    {{- with .Values.hyperdx.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end -}}
    {{- end }}
spec:
  {{- if not .Values.hyperdx.autoscaling.enabled }}
  replicas: {{ .Values.hyperdx.deployment.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clickstack.selectorLabels" . | nindent 6 }}
      app: {{ include "clickstack.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "clickstack.selectorLabels" . | nindent 8 }}
        app: {{ include "clickstack.fullname" . }}
      annotations:
      {{- if .Values.hyperdx.deployment.annotations }}
        {{- with .Values.hyperdx.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end -}}
      {{- end }}
    spec:
      {{- if .Values.hyperdx.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.hyperdx.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.hyperdx.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.hyperdx.deployment.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.hyperdx.deployment.priorityClassName }}
      priorityClassName: {{ .Values.hyperdx.deployment.priorityClassName | quote }}
      {{- end }}
      {{- if or .Values.hyperdx.serviceAccount.create .Values.hyperdx.serviceAccount.name }}
      serviceAccountName: {{ .Values.hyperdx.serviceAccount.name | default (include "clickstack.hyperdx.fullname" .) }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if or .Values.mongodb.enabled .Values.hyperdx.deployment.initContainers }}
      initContainers:
        {{- if .Values.mongodb.enabled }}
        - name: wait-for-mongodb
          image: {{ .Values.hyperdx.deployment.waitForMongodb.image }}
          imagePullPolicy: {{ .Values.hyperdx.deployment.waitForMongodb.pullPolicy }}
          command: ['sh', '-c', 'until nc -z {{ include "clickstack.mongodb.svc" . }} 27017; do echo waiting for mongodb; sleep 2; done;']
        {{- end }}
        {{- with .Values.hyperdx.deployment.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.hyperdx.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.hyperdx.deployment.image.repository }}:{{ .Values.hyperdx.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hyperdx.deployment.image.pullPolicy }}
          ports:
            - name: app-port
              containerPort: {{ .Values.hyperdx.ports.app }}
            - name: api-port
              containerPort: {{ .Values.hyperdx.ports.api }}
            - name: opamp-port
              containerPort: {{ .Values.hyperdx.ports.opamp }}
          {{- if .Values.hyperdx.deployment.resources }}
          resources:
            {{- toYaml .Values.hyperdx.deployment.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.hyperdx.deployment.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.hyperdx.ports.api }}
            initialDelaySeconds: {{ .Values.hyperdx.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hyperdx.deployment.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hyperdx.deployment.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.hyperdx.deployment.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.hyperdx.deployment.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.hyperdx.ports.api }}
            initialDelaySeconds: {{ .Values.hyperdx.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hyperdx.deployment.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hyperdx.deployment.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.hyperdx.deployment.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.hyperdx.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: clickstack-config
            {{- if ne .Values.hyperdx.secrets nil }}
            - secretRef:
                name: clickstack-secret
            {{- end }}
          env:
            {{- if .Values.hyperdx.deployment.useExistingConfigSecret }}
            - name: DEFAULT_CONNECTIONS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hyperdx.deployment.existingConfigSecret | quote }}
                  key: {{ .Values.hyperdx.deployment.existingConfigConnectionsKey | quote }}
                  optional: false
            - name: DEFAULT_SOURCES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hyperdx.deployment.existingConfigSecret | quote }}
                  key: {{ .Values.hyperdx.deployment.existingConfigSourcesKey | quote }}
                  optional: false
            {{- else }}
            {{- if and .Values.hyperdx.deployment.defaultConnections (ne .Values.hyperdx.secrets nil) }}
            - name: DEFAULT_CONNECTIONS
              value: {{ tpl .Values.hyperdx.deployment.defaultConnections . | quote }}
            {{- end }}
            {{- if .Values.hyperdx.deployment.defaultSources }}
            - name: DEFAULT_SOURCES
              value: {{ tpl .Values.hyperdx.deployment.defaultSources . | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.hyperdx.deployment.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
{{- end }}
