variable "cluster_name" {}
variable "zone" {}
variable "k8s_version" {}
variable "node_machine_type" {}
variable "desired_node_count" {}
variable "min_node_count" {}
variable "max_node_count" {}
variable "node_disk_size_gb" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "spot_enabled" {}