apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egov-localization-qa
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: "egov-localization:qa"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/egovernments/DIGIT-DevOps.git
    targetRevision: sample-app-argocd-kargo
    path: deploy-as-code/helm/charts/core-services/egov-localization
    helm:
      valueFiles:
        - ../../common/values.yaml
        - values.yaml
        - ../../../../../gitops/egov-localization/values-qa.yaml
      parameters:
        - name: image.tag
          value: "redis-localization-key-5c0a4c4"
        - name: initContainers.dbMigration.image.tag
          value: "redis-localization-key-5c0a4c4"
        - name: disableAnnotationTimestamp
          value: "true"
  destination:
    name: unified-qa
    namespace: egov
  syncPolicy: {}
