apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: egov-localization
  namespace: egov-localization
spec:
  interval: 5m
  subscriptions:
    - image:
        repoURL: egovio/egov-localization
        imageSelectionStrategy: NewestBuild
        ignoreTagsRegexes:
          - "^latest$"
          - "-amd64$"
          - "-arm64$"
        discoveryLimit: 10
