{{- with index .Values "cluster-configs" "secrets" "airflow-jwt-secret" }}
{{- if index . "jwt-secret" }}
{{- $cfg := . }}
{{- $namespaces := .namespace }}
{{- if kindIs "string" $namespaces }}{{- $namespaces = list $namespaces }}{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cfg.name | default "backbone-airflow-jwt-secret" }}
  namespace: {{ $ns }}
type: Opaque
data:
  jwt-secret: {{ index $cfg "jwt-secret" | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}
