{{- with index .Values "cluster-configs" "secrets" "airflow-admin-credentials" }}
{{- if .password }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "airflow-admin-credentials" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "airflow-admin-credentials" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "airflow-admin-credentials" "password" | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}
