{{- with index .Values "cluster-configs" "secrets" "citizen-broker-secret" }}
{{- if index . "citizen-broker-client-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  citizen-broker-client-secret: {{ index . "citizen-broker-client-secret" | b64enc | quote }}
{{- end }}
{{- end }}