{{- $filestore := index .Values "egov-filestore" }}
{{- if $filestore }}
{{- if index $filestore "is-azure-enabled" }}
{{- with index .Values "cluster-configs" "secrets" "egov-filestore-azure" }}
{{- if index . "account-key" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  account-name: {{ index . "account-name" | b64enc | quote }}
  account-key: {{ index . "account-key"  | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
