{{- with index .Values "cluster-configs" "secrets" "egov-notification-push" }}
{{- if index . "fcm-service-account-key-json" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  fcm-service-account-key-json: {{ index . "fcm-service-account-key-json" | b64enc | quote }}
{{- end }}
{{- end }}
