{{- with index .Values "cluster-configs" "secrets" "employee-iam-secret" }}
{{- if index . "employee-iam-client-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  employee-iam-client-secret: {{ index . "employee-iam-client-secret" | b64enc | quote }}
{{- end }}
{{- end }}
