{{- with index .Values "cluster-configs" "secrets" "github-config" }}
{{- if index . "gitAppId" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "github-config" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  gitAppId: {{ index $.Values "cluster-configs" "secrets" "github-config" "gitAppId" | int64 | toString | b64enc | quote }}
  gitAppInstallationId: {{ index $.Values "cluster-configs" "secrets" "github-config" "gitAppInstallationId" | int64 | toString | b64enc | quote }}
  gitAppPrivateKey: {{ index $.Values "cluster-configs" "secrets" "github-config" "gitAppPrivateKey" | b64enc | quote }}
  kubeToken: {{ index $.Values "cluster-configs" "secrets" "github-config" "kubeToken" | default "" | b64enc | quote }}
  kubeapiurl: {{ index $.Values "cluster-configs" "secrets" "github-config" "kubeapiurl" | default "" | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}