{{- with index .Values "cluster-configs" "secrets" "grafana" }}
{{- if index . "clientID" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  GF_AUTH_GITHUB_CLIENT_ID: {{ index . "clientID" | b64enc | quote }}
  GF_AUTH_GITHUB_CLIENT_SECRET: {{ index . "clientSecret" | b64enc | quote }}
{{- end }}
{{- end }}
