{{- with index .Values "cluster-configs" "secrets" "grafana-admin" }}
{{- if index . "adminPassword" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  admin-user: {{ index . "adminUser" | default "admin" | b64enc | quote }}
  admin-password: {{ index . "adminPassword" | b64enc | quote }}
{{- end }}
{{- end }}
