{{- with index .Values "cluster-configs" "secrets" "license-certificate" }}
{{- if index . "certificate-otp-bypass-code" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "license-certificate" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
 certificate-otp-bypass-code: {{ index $.Values "cluster-configs" "secrets" "license-certificate" "certificate-otp-bypass-code" | b64enc | quote }}
 egov-keycloak-client-secret: {{ index $.Values "cluster-configs" "secrets" "license-certificate" "egov-keycloak-client-secret" | b64enc | quote }}
 {{- end }}
---
{{- end }}
{{- end }}
