{{- with index .Values "cluster-configs" "secrets" "radiology-secrets" }}
{{- if index . "LDAP_ADMIN_PASSWORD" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "radiology-secrets" "name" | default "radiology-secrets" }}
  namespace: {{ $ns }}
  labels:
    app: care-radiology
type: Opaque
stringData:
{{- range $key, $value := index $.Values "cluster-configs" "secrets" "radiology-secrets" }}
{{- if and (ne $key "namespace") (ne $key "name") }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
