{{- with index .Values "cluster-configs" "secrets" "referralmanagement" }}
{{- if index . "s3-secret-key" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  s3-key: {{ index . "s3-key" | b64enc | quote }}
  s3-secret-key: {{ index . "s3-secret-key"  | b64enc | quote }}
{{- end }}
{{- end }}