{{- with index .Values "cluster-configs" "secrets" "sso" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  {{- if index . "auth-sso-default-password-override-tg-oidc-azure" }}
  auth-sso-default-password-override-tg-oidc-azure: {{ index . "auth-sso-default-password-override-tg-oidc-azure" | b64enc | quote }}
  {{- end }}
  {{- if index . "auth-sso-default-password-override-mz-oidc-google" }}
  auth-sso-default-password-override-mz-oidc-google: {{ index . "auth-sso-default-password-override-mz-oidc-google" | b64enc | quote }}
  {{- end }}
  {{- if index . "auth-user-default-password" }}
  auth-user-default-password: {{ index . "auth-user-default-password" | b64enc | quote }}
  {{- end }}
  {{- if index . "graph-client-secret-tg-oidc-azure" }}
  graph-client-secret-tg-oidc-azure: {{ index . "graph-client-secret-tg-oidc-azure" | b64enc | quote }}
  {{- end }}
  {{- if index . "graph-client-secret-mz-oidc-google" }}
  graph-client-secret-mz-oidc-google: {{ index . "graph-client-secret-mz-oidc-google" | b64enc | quote }}
  {{- end }}
{{- end }}