{{- with index .Values "cluster-configs" "secrets" "sso" }}
{{- if index . "auth-sso-default-password-override-tg-oidc-azure" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  auth-sso-default-password-override-tg-oidc-azure: {{ index . "auth-sso-default-password-override-tg-oidc-azure" | b64enc | quote }}
  auth-user-default-password: {{ index . "auth-user-default-password" | b64enc | quote }}
  graph-client-secret-tg-oidc-azure: {{ index . "graph-client-secret-tg-oidc-azure" | b64enc | quote }}
{{- end }}
{{- end }}