{{- with index .Values "cluster-configs" "secrets" "superset" }}
{{- if index . "SECRET_KEY" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "superset" "name" | default "superset-secret" }}
  namespace: {{ $ns }}
  labels:
    app: superset
type: Opaque
stringData:
{{- range $key, $value := index $.Values "cluster-configs" "secrets" "superset" }}
{{- if and (ne $key "namespace") (ne $key "name") }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
