namespace: kube-system

image:
  repository: tonistiigi/binfmt
  tag: qemu-v8.1.5
  pullPolicy: Always

# Architectures to register QEMU handlers for.
# arm64 is required for building linux/arm64 images on AMD64 nodes.
platforms: "arm64"

updateStrategy: RollingUpdate

# Run on only tainted node for jenkins
tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: egov-jenkins

resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 10m
    memory: 16Mi

nodeSelector:
  dedicated: egov-jenkins
