output "zookeeper_storage_ids" {
  value = "${module.zookeeper.storage_ids}"
}

output "kafka_storage_ids" {
  value = "${module.kafka.storage_ids}"
}

output "es_master_storage_ids" {
  value = "${module.es-master.storage_ids}"
}

output "es_data_v1_storage_ids" {
  value = "${module.es-data-v1.storage_ids}"
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.kubernetes.kube_config
  sensitive = true
}

output "db_name" {
  description = "Name of the database"
  value       = module.postgres-db.db_name
}

output "db_host" {
  description = "DB Host"
  value       = module.postgres-db.db_host
}
