templates:
  default: &default
    chart: ./{{`{{ .Release.Name }}`}}
    namespace: egov
    missingFileHandler: Warn
    values:
      - ../../environments/egov-demo-secrets.yaml
      - ../../environments/egov-demo.yaml
      - ./{{`{{ .Release.Name }}`}}/values.yaml

releases:
  - name: idgen
    installed: true
    <<: *default

  - name: mdms-v2
    installed: true
    <<: *default

  - name: localization
    installed: true
    <<: *default

  - name: boundary
    installed: true
    <<: *default

  - name: keycloak
    installed: true
    <<: *default

  - name: individual
    installed: true
    <<: *default

  - name: account
    installed: true
    <<: *default

  - name: registry
    installed: true
    <<: *default

  - name: rbac
    installed: true
    needs:
      - keycloak
    <<: *default

  - name: otp
    installed: true
    <<: *default

  - name: hrms
    installed: true
    <<: *default

  - name: workflow
    installed: true
    <<: *default

  - name: notification
    installed: true
    <<: *default

  - name: filestore
    installed: true
    <<: *default

  - name: pdf
    installed: true
    <<: *default

  - name: url-shortener
    installed: true
    <<: *default

  - name: gateway-kong
    installed: true
    <<: *default
