# Common Labels
labels:
  app: "project-factory"
  group: "rainmaker"

namespace: health

# Ingress Configs
ingress:
  namespace: egov
  enabled: true
  zuul: true
  context: "project-factory"
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "project_factory_health_schema"
    image:
      repository: "project-factory-db"

# Container Configs
image:
  repository: "project-factory"
replicas: "3"
appType: "java-spring"
tracing-enabled: true
heap: '-Xmx1000m -Xms756m'
memory_limits: '3Gi'
cpu_limits: '2048m'

# Additional Container Envs
env: |
  - name: KAFKA_BROKER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers

  - name: KAFKA_SAVE_CAMPAIGN_DETAILS_TOPIC
    value: save-campaign-details

  - name: KAFKA_UPDATE_CAMPAIGN_DETAILS_TOPIC
    value: update-campaign-details

  - name: BASE_SECRET
    valueFrom:
      secretKeyRef:
        name: project-factory
        key: basesecret

  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service

  - name: EGOV_MDMS_V2_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: mdms-service-v2

  - name: EGOV_FILESTORE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore

  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen

  - name: EXCEL_INGESTION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: excel-ingestion

  - name: EGOV_FACILITY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: facility

  - name: EGOV_BOUNDARY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: boundary-service

  - name: EGOV_PROJECT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-project

  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user

  - name: EGOV_PRODUCT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: product

  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-hrms

  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization

  - name: EGOV_HEALTH_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-individual

  - name: EGOV_AUDIT_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: audit-service

  - name: EGOV_PLAN_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: plan-service

  - name: EGOV_CENSUS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: census-service

  - name: EGOV_SERVICE_REQUEST_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: health-service-request

  - name: CONTEXT_PATH
    value: "/project-factory"

  - name: FILE_STORE_SERVICE_END_POINT
    value: filestore/v1/files

  - name: EGOV_MDMS_V2_SEARCH_ENDPOINT
    value: {{ .Values.mdmsV2SearchEndpoint | default "egov-mdms-service/v2/_search" }}

  - name: EGOV_MDMS_V2_CREATE_ENDPOINT
    value: {{ .Values.mdmsV2CreateEndpoint | default "egov-mdms-service/v2/_create" }}

  - name: EGOV_MDMS_V2_UPDATE_ENDPOINT
    value: {{ .Values.mdmsV2UpdateEndpoint | default "egov-mdms-service/v2/_update" }}

  - name: EGOV_MDMS_V1_SEARCH_ENDPOINT
    value: {{ .Values.mdmsV1SearchEndpoint | default "egov-mdms-service/v1/_search" }}

  - name: EGOV_IDGEN_PATH
    value: egov-idgen/id/_generate

  - name: EGOV_MDMS_SCHEMA_PATH
    value: {{ .Values.mdmsV1SchemaSearchEndpoint | default "egov-mdms-service/v1/_search" }}

  - name: EGOV_MDMS_DATA_PATH
    value: {{ .Values.mdmsV1DataSearchEndpoint | default "egov-mdms-service/v1/_search" }}

  - name: EGOV_PROJECT_SEARCH_PATH
    value: project/v1/_search

  - name: EGOV_PROJECT_CREATE_PATH
    value: project/v1/_create

  - name: EGOV_FACILITY_SEARCH_PATH
    value: facility/v1/_search

  - name: EGOV_PRODUCT_SEARCH_PATH
    value: product/v1/_search

  - name: EGOV_PRODUCT_VARIANT_SEARCH_PATH
    value: product/variant/v1/_search

  - name: EGOV_STAFF_SEARCH_PATH
    value: staff/v1/_search

  - name: EGOV_USER_SEARCH_PATH
    value: user/_search

  - name: EGOV_USER_CREATE_PATH
    value: user/users/_createnovalidate

  - name: EGOV_BOUNDARY_HIERARCHY_SEARCH_PATH
    value: boundary-service/boundary-hierarchy-definition/_search

  - name: EGOV_BOUNDARY_SEARCH_PATH
    value: boundary-service/boundary/_search

  - name: EGOV_LOCALIZATION_SEARCH_PATH
    value: localization/messages/v1/_search

  - name: EGOV_HEALTH_INDIVIDUAL_SEARCH_PATH
    value: individual/v1/_search

  - name: EGOV_HEALTH_INDIVIDUAL_CREATE_PATH
    value: individual/v1/_create

  - name: EGOV_PLAN_SEARCH_PATH
    value: plan-service/plan/v1/_search

  - name: EGOV_CENSUS_SEARCH_PATH
    value: census-service/census/v1/_search

  - name: EGOV_SERVICE_REQUEST_SEARCH_PATH
    value: service-request/v1/_search

  - name: EGOV_SERVICE_REQUEST_CREATE_PATH
    value: service-request/v1/_create

  - name: CAMPAIGN_SCHEMA_NAME
    value: campaign

  - name: RESOURCE_SCHEMA_NAME
    value: resource

  - name: PROJECT_TYPE
    value: campaign

  - name: STAFF_ROLE
    value: HEALTH_FACILITY_WORKER

  - name: STAFF_TYPE
    value: frontlineWorker

  - name: CMP_IDGEN_FORMAT
    value: CMP-[cy:yyyy-MM-dd]-[SEQ_EG_CMP_ID]

  - name: CMP_IDGEN_IDNAME
    value: campaign.number

  - name: VALIDATE_CAMPAIGN_ID_IN_METADATA
    value: {{ .Values.validateCampaignIdInMetadata | default "false" | quote }}

  - name: NOT_CREATE_USER_IF_ALREADY_THERE
    value: {{ .Values.notCreateUserIfAlreadyThere | default "false" | quote }}

  - name: INCOMING_REQUEST_PAYLOAD_LIMIT
    value: 5mb
