apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: unified-dev-health-appset-frontend
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: console
          - name: dashboard-ui
          - name: microplan-ui
          - name: payments-ui
          - name: workbench-ui
          - name: health-ui

  template:
    metadata:
      name: 'health-{{name}}'

    spec:
      project: health-project

      source:
        repoURL: https://github.com/egovernments/DIGIT-DevOps.git
        targetRevision: unified-env-lts
        path: deploy-as-code/helm/charts/frontend/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../environments/unified-health-dev.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: 'health'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
