apiVersion: v2
name: boundary-management
description: Boundary Management utility (Node.js/TypeScript) - Excel template generate/process front for the digit3 boundary service
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

dependencies:
- name: common
  version: 0.0.5
  repository: file://../../common
