{{- if and .Values.certManager.enable .Values.metrics.enable .Values.metrics.secure }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "clickhouse-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "clickhouse-operator.resourceName" (dict "suffix" "metrics-certs" "context" $) }}
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - clickhouse-operator-metrics-service.{{ .Values.namespace }}.svc
  - clickhouse-operator-metrics-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
  {{- if .Values.certManager.issuerRef}}
    {{ .Values.certManager.issuerRef | toYaml | nindent 4 }}
  {{- else }}
    kind: Issuer
    name: {{ include "clickhouse-operator.resourceName" (dict "suffix" "selfsigned-issuer" "context" $) }}
  {{- end }}
  secretName: metrics-server-cert
{{- end }}
