{{- $envValues := index .Values (default .Chart.Name .Values.name) | default dict -}}
{{- $serviceMonitor := or $envValues.serviceMonitor .Values.serviceMonitor -}}
{{- if and $serviceMonitor $serviceMonitor.enabled }}
{{- template "common.servicemonitor" . -}}
{{- end }}

