apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
    group: core
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
      protocol: TCP
      name: http
  selector:
    app: keycloak
