# Common Labels
labels:
  app: "boundary"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "boundary"


# Container Configs

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "boundary_schema"
    image:
      repository: "boundary-db"
    env: |
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
        - name: "FLYWAY_USER"
          valueFrom:
            secretKeyRef:
                name: db
                key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef:
                name: db
                key: flyway-password
        - name: JAVA_ENABLE_DEBUG
          value: "TRUE"
        - name: "FLYWAY_LOCATIONS"
          valueFrom:
            configMapKeyRef:
                name: egov-config
                key: flyway-locations
        - name: FLYWAY_SCHEMAS
          value: public
        - name: FLYWAY_DEFAULT_SCHEMA
          value: public

# Container Configs
image:
  repository: "boundary"
replicas: 1
appType: "go"
tracing-enabled: true # Assuming you want to keep tracing
healthChecks:
  enabled: false # Disabled as requested
  livenessProbePath: "/health"
  readinessProbePath: "/health"
# Resource configuration for Go service
resources: |
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

# Additional Container Envs
env: |
  - name: DB_HOST
    value: "postgresql-lts.egov"
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: DB_NAME
    value: "postgres"
  - name: DB_SSL_MODE
    value: "disable"
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: "/boundary"
  - name: BOUNDARY_BASEPATH
    value: "http://boundary:8080/"
  - name: FILESTORE_BASEPATH
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: filestore
  - name: FILESTORE_ENDPOINT
    value: "/filestore/v1/files"
  - name: CACHE_TYPE
    value: "inmemory"
  # If you want to use Redis, uncomment and set these:
  # - name: CACHE_TYPE
  #   value: "redis"
  # - name: CACHE_REDIS_ADDR
  #   value: "localhost:6379"
  # - name: CACHE_REDIS_DB
  #   value: "0" 
  - name: OTEL_TRACES_EXPORTER
    value: "none"
  - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    value: "org.postgresql.Driver"
  - name: JAEGER_SERVICE_NAME
    value: boundary
  - name: JAEGER_SAMPLER_TYPE
    value: remote
  - name: JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: JAEGER_AGENT_PORT
    value: "6831"
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: $(JAEGER_AGENT_HOST):5778
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  - name: OTEL_ENABLED
    value: "true"
  - name: OTEL_SERVICE_NAME
    value: boundary
  - name: OTEL_SERVICE_VERSION
    value: 1.0.0
  - name: OTEL_METRICS_ENABLED
    value: "true"
  - name: PROMETHEUS_PORT
    value: "9090"
  - name: OTEL_TRACES_SAMPLER_ARG
    value: "1.0"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: open-telemetry-opentelemetry-collector.monitoring.svc.cluster.local:4318
  - name: MIGRATION_ENABLED
    value: "true"
  - name: MIGRATION_DB_URL
    value: "your_database_url_here"
  - name: MIGRATION_FLYWAY_USER
    value: postgres
  - name: MIGRATION_FLYWAY_PASSWORD
    value: your_flyway_password_here
  - name: MIGRATION_KAFKA_BROKERS
    value: release-name-kafka-controller-headless.kafka-kraft:9092
  - name: MIGRATION_KAFKA_TOPIC
    value: createSchemaV2
  - name: MIGRATION_KAFKA_GROUP_ID
    value: boundary-migration-2
  - name: PUBSUB_ENABLED
    value: "true"
  - name: PUBSUB_TYPE
    value: redis
  - name: KAFKA_BROKERS
    value: release-name-kafka-controller-headless.kafka-kraft:9092
  - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
    value: "true"
  - name: KAFKA_PARTITION_COUNT
    value: "1"
  - name: KAFKA_REPLICATION_FACTOR
    value: "1"
  - name: KAFKA_CONSUMER_GROUP
    value: boundary-service
  - name: REDIS_ADDRESS
    value: redis.backbone.svc.cluster.local:6379
  - name: REDIS_PASSWORD
  - name: REDIS_DB
    value: "0"
  - name: REDIS_CONSUMER_GROUP
    value: boundary-service
  - name: REDIS_CONSUMER_ID
    value: boundary-service-1
  - name: REDIS_RETENTION_DAYS
    value: "7"
  - name: REDIS_MAX_STREAM_LENGTH
    value: "1000000"
  - name: REDIS_CLEANUP_INTERVAL
    value: "86400"
  - name: PUBSUB_TOPIC_CREATE_BOUNDARY
    value: boundary-create-boundary
  - name: PUBSUB_TOPIC_UPDATE_BOUNDARY
    value: boundary-update-boundary
  - name: PUBSUB_TOPIC_DELETE_BOUNDARY
    value: boundary-delete-boundary
  - name: PUBSUB_TOPIC_CREATE_BOUNDARY_HIERARCHY
    value: boundary-create-boundary-hierarchy
  - name: PUBSUB_TOPIC_UPDATE_BOUNDARY_HIERARCHY
    value: boundary-update-boundary-hierarchy
  - name: PUBSUB_TOPIC_DELETE_BOUNDARY_HIERARCHY
    value: boundary-delete-boundary-hierarchy
  - name: PUBSUB_TOPIC_CREATE_BOUNDARY_RELATIONSHIP
    value: boundary-create-boundary-relationship
  - name: PUBSUB_TOPIC_UPDATE_BOUNDARY_RELATIONSHIP
    value: boundary-update-boundary-relationship
  - name: PUBSUB_TOPIC_DELETE_BOUNDARY_RELATIONSHIP
    value: boundary-delete-boundary-relationship
  - name: SCHEMA_SEPARATION_MODE
    value: "false"
  - name: SCHEMA_SEPARATION_TOPIC
    value: account-migration
  - name: MIGRATION_FLYWAY_LOCATIONS
    value: filesystem:/opt/digit/db/migrations
  - name: MIGRATION_SCRIPT_PATH
    value: /opt/digit/migrate.sh
  - name: MIGRATION_FLYWAY_BIN
    value: /opt/flyway/flyway
  - name: MIGRATION_SCHEMA_TABLE
    value: boundary_schema
