{{- with index .Values "cluster-configs" "secrets" "egov-metabase" }}
{{- if index . "egov-metabase-api-key" }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "egov-metabase" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
 egov-metabase-api-key: {{ index $.Values "cluster-configs" "secrets" "egov-metabase" "egov-metabase-api-key" | b64enc | quote }}
 egov-metabase-secret-key: {{ index $.Values "cluster-configs" "secrets" "egov-metabase" "egov-metabase-secret-key" | b64enc | quote }}
 {{- end }}
{{- end }}
{{- end }}