{{- with index .Values "cluster-configs" "secrets" "hmac-secret" }}
{{- if index . "hmac-secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  hmac-secret: {{ index $.Values "cluster-configs" "secrets" "hmac-secret" "hmac-secret" | b64enc | quote }}
{{- end }}
{{- end }}
