variable "tenancy_id" {}    
variable "ClusterName" {}
variable "kubernetes_version" {}
variable "Shape" {}    
variable "node_pool_size" {}
variable "availability_domain" {}
variable "vcn_id" {}    
variable "private_subnet_id" {}
variable "public_subnet_id" {}
variable "service_lb_subnet_ids" {}