apiVersion: v2
name: care-traefik
description: Traefik ingress controller for care namespace
type: application
version: 0.1.0
appVersion: "3.1.0"
dependencies:
- name: traefik
  version: "30.1.0"
  repository: https://helm.traefik.io/traefik
