# Common Labels
labels:
  app: "license-admin"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  zuul: false
  context: "license/admin"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "license-admin"
  tag: "latest"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/license/admin/health"
  readinessProbePath: "/license/admin/health"

resources: |
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    cpu: "300m"
    memory: "800Mi"
