environments:
  unified-dev:
    values:
      - namespace: monitoring
      - ../../environments/unified-dev.yaml
    secrets:
      - ../../environments/unified-dev-secrets.yaml
  unified-qa:
    values:
      - namespace: monitoring
      - ../../environments/unified-qa.yaml
    secrets:
      - ../../environments/unified-qa-secrets.yaml

---

repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

templates:
  default: &default
    labels:
      target: ./{{`{{ .Release.Name }}`}}
    missingFileHandler: Warn

releases:

- name: loki-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/loki-stack
  version: 2.10.1
  <<: *default
  values:
  - ./values/loki-stack.yaml
  - loki:
      persistence: {{ .Values.loki.persistence | toYaml | nindent 8 }}
      {{- if hasKey .Values.loki "livenessProbe" }}
      livenessProbe: {{ .Values.loki.livenessProbe | toYaml | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values.loki "readinessProbe" }}
      readinessProbe: {{ .Values.loki.readinessProbe | toYaml | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values.loki "nodeSelector" }}
      nodeSelector: {{ .Values.loki.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values.loki "tolerations" }}
      tolerations: {{ .Values.loki.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if hasKey .Values.loki "securityContext" }}
      securityContext: {{ .Values.loki.securityContext | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.loki.additionalConfigs }}
      config:
        schema_config: {{ .Values.loki.additionalConfigs.schema_config | toYaml | nindent 10 }}
        storage_config: {{ .Values.loki.additionalConfigs.storage_config | toYaml | nindent 10 }}
        compactor: {{ .Values.loki.additionalConfigs.compactor | toYaml | nindent 10 }}
        table_manager: {{ .Values.loki.additionalConfigs.table_manager | toYaml | nindent 10 }}
        {{- if hasKey .Values.loki.additionalConfigs "limits_config" }}
        limits_config: {{ .Values.loki.additionalConfigs.limits_config | toYaml | nindent 10 }}
        {{- end }}
        {{- if hasKey .Values.loki.additionalConfigs "chunk_store_config" }}
        chunk_store_config: {{ .Values.loki.additionalConfigs.chunk_store_config | toYaml | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.loki.serviceAccount.annotations }}
      serviceAccount:
        annotations: {{ .Values.loki.serviceAccount.annotations | toYaml | nindent 10 }}
      {{- end }}
  {{- if hasKey .Values "promtail" }}
  - promtail:
      {{- if .Values.promtail.tolerations }}
      tolerations: {{ .Values.promtail.tolerations | toYaml | nindent 8 }}
      {{- end }}
  {{- end }}

- name: kube-prometheus-stack
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: prometheus-community/kube-prometheus-stack
  version: 56.6.2
  disableValidation: true
  <<: *default
  values:
  - ./values/prometheus.yaml
  - alertmanager:
      enabled: {{ .Values.prometheus.alertmanager.enabled }}
  {{- if .Values.prometheus.alertmanager.enabled }}
  - alertmanager:
      config: {{ index .Values "cluster-configs" "secrets" "alertmanager" "config" | toYaml | nindent 8 }}
  {{- end }}
  - prometheus:
      prometheusSpec:
        additionalScrapeConfigs: {{ .Values.prometheus.additionalScrapeConfigs | toYaml | nindent 8 }}
        externalLabels: {{ .Values.prometheus.externalLabels | toYaml | nindent 10 }}

- name: jaeger
  installed: false
  namespace: es-cluster
  chart: jaegertracing/jaeger
  version: 0.35.0
  <<: *default
  values:
    - ./values/jaeger.yaml
  set:
    - name: query.ingress.hosts[0]
      value: "{{ .Values.global.domain }}"

- name: grafana
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: grafana/grafana
  version: 7.3.0
  <<: *default
  values:
    - ./values/grafana.yaml
    - grafana.ini:
        auth.github:
          allowed_organizations: {{ .Values.grafana.github.allowed_organizations }}
          role_attribute_path: {{ .Values.grafana.github.role_attribute_path }}
    - envRenderSecret:
        GF_AUTH_GITHUB_CLIENT_ID: {{ index .Values "cluster-configs" "secrets" "grafana" "clientID" }}
        GF_AUTH_GITHUB_CLIENT_SECRET: {{ index .Values "cluster-configs" "secrets" "grafana" "clientSecret" }}
  set:
    - name: ingress.hosts[0]
      value: "{{ .Values.global.domain }}"
    - name: ingress.tls[0].hosts[0]
      value: "{{ .Values.global.domain }}"
    - name: ingress.tls[0].secretName
      value: "{{ .Values.global.domain }}-tls-certs"

- name: blackbox
  installed: true
  namespace: {{ .Values.namespace | default "default-namespace" }}
  chart: ../backbone-services/prometheus-blackbox-exporter
  version: 8.2.0
  <<: *default