# Common Labels
labels:
  app: "account-java"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "account-java"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "account_schema"
    image:
      repository: "account-java-db"
    env: |
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
        - name: "FLYWAY_USER"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-password
        - name: JAVA_ENABLE_DEBUG
          value: "TRUE"
        - name: "FLYWAY_LOCATIONS"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: flyway-locations
        - name: FLYWAY_SCHEMAS
          value: public
        - name: FLYWAY_DEFAULT_SCHEMA
          value: public

# Container Configs
image:
  repository: "account-java"
replicas: 1
appType: "java"
tracing-enabled: false
heap: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0"
healthChecks:
  enabled: false
  livenessProbePath: "/account-java/actuator/health/liveness"
  readinessProbePath: "/account-java/actuator/health/readiness"
# Resource configuration for the Java service
resources: |
  requests:
    cpu: "150m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1.5Gi"

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: CONTEXT_PATH
    value: /account-java
    
  - name: DB_HOST
    value: postgres.egov
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: db
  - name: DB_NAME
    value: postgres
  - name: DB_SSL_MODE
    value: disable

  - name: KEYCLOAK_BASE_URL
    value: http://keycloak.keycloak.svc.cluster.local:8080/keycloak
  - name: KEYCLOAK_ADMIN_USER
    value: digit
  - name: KEYCLOAK_ADMIN_PASS
    valueFrom:
      secretKeyRef:
        name: kc-admin
        key: password
  - name: CITIZEN_BROKER_CLIENT_ID
    value: citizen-broker
  - name: CITIZEN_BROKER_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: citizen-broker-secret
        key: citizen-broker-client-secret

  - name:EMPLOYEE_IAM_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: employee-iam-secret
        key: employee-iam-client-secret

  - name: NOTIFICATION_BASE_URL
    valueFrom:
      configMapKeyRef:
        key: notification
        name: egov-service-host


  - name: OTP_BASE_URL
    valueFrom:
      configMapKeyRef:
        key: otp-java
        name: egov-service-host
  - name: OTP_GENERATE_PATH
    value: otp-java/v3/generate
  - name: OTP_VERIFY_PATH
    value: otp-java/v3/verify
  - name: OTP_RESEND_PATH
    value: otp-java/v3/resend
  - name: OTP_TIMEOUT_SECONDS
    value: "10"

  - name: OTEL_ENABLED
    value: "false"
  - name: OTEL_SERVICE_NAME
    value: account-java
  - name: OTEL_SERVICE_VERSION
    value: 1.0.0
  - name: OTEL_METRICS_ENABLED
    value: "false"
  - name: PROMETHEUS_PORT
    value: "9090"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: open-telemetry-opentelemetry-collector.monitoring.svc.cluster.local:4318
  - name: CONSOLE_LOGS_ENABLED
    value: "true"

  - name: PUBSUB_ENABLED
    value: "false"
  - name: PUBSUB_TYPE
    value: redis
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config

  - name: REDIS_ADDRESS
    value: redis.backbone.svc.cluster.local:6379
  - name: REDIS_HOST
    value: redis.backbone.svc.cluster.local
  - name: REDIS_PORT
    value: "6379"

  - name: PUBSUB_TOPIC_CREATE_TENANT
    value: account-create-tenant
  - name: PUBSUB_TOPIC_UPDATE_TENANT
    value: account-update-tenant
  - name: PUBSUB_TOPIC_DELETE_TENANT
    value: account-delete-tenant
  - name: PUBSUB_TOPIC_CREATE_TENANT_CONFIG
    value: account-create-tenant-config
  - name: PUBSUB_TOPIC_UPDATE_TENANT_CONFIG
    value: account-update-tenant-config
  - name: PUBSUB_TOPIC_MIGRATION
    value: account-migration
  - name: OTP_PLATFORM_TENANT
    value: default
  - name: LOG_LEVEL
    value: DEBUG
