apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: unified-dev-egov-appset-backbone
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: oauth2-proxy

  template:
    metadata:
      name: 'egov-{{name}}'

    spec:
      project: egov-project

      source:
        repoURL: https://github.com/egovernments/DIGIT-DevOps.git
        targetRevision: unified-env-lts
        path: deploy-as-code/helm/charts/backbone-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../environments/unified-dev.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: 'egov'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
