apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: egov-project
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:egovernments/DIGIT-DevOps.git

  destinations:
    - namespace: 'egov'
      server: https://kubernetes.default.svc
