apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: digit-lts-egov-appset-core
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: license-admin
          - name: license-citizen
          - name: license-employee
          - name: license-certificate
          - name: pdf-v3
          - name: metabase
          - name: vc
          - name: boundary-java
          - name: license-validator
          - name: walt
          - name: account-java
          - name: apportion
          - name: billing-java
          - name: calculator
          - name: employee-java
          - name: filestore-java
          - name: gateway
          - name: idgen-java
          - name: individual-java
          - name: internal-gateway-scg
          - name: gateway-kong
          - name: localization-java
          - name: mdms-v2
          - name: notification-java
          - name: otp-java
          - name: pdf
          - name: pg-service
          - name: registry-java
          - name: schema-registry
          - name: url-shortener-java
          - name: user-otp
          - name: workflow-java

  template:
    metadata:
      name: 'egov-{{name}}'

    spec:
      project: egov-project

      source:
        repoURL: https://github.com/egovernments/DIGIT-DevOps.git
        targetRevision: digit-lts
        path: deploy-as-code/helm/charts/core-services/{{name}}
        helm:
          valueFiles:
            - values.yaml
            - ../../../environments/test-lts.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: 'egov'

      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
