# Common Labels
labels:
  app: "license-citizen"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "license/citizen"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "license-citizen"
  tag: "latest"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/license-citizen/health"
  readinessProbePath: "/license-citizen/health"

# Additional Container Envs
env: |
  - name: API_PROXY_TARGET
    value: "https://digit-lts.digit.org/license"

resources: |
  requests:
    cpu: "100m"
    memory: "300Mi"
  limits:
    cpu: "300m"
    memory: "800Mi"
