# Common Labels
labels:
  app: "pdf-v3"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pdf-v3"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pdf_v3_schema"
    image:
      repository: "pdf-v3-db"

# Container Configs
image:
  repository: "pdf-v3"
replicas: "1"
appType: "java-spring"
heap: "-Xmx512m -Xms512m"
memory_limits: 1024Mi

# Additional Container Envs
env: ""
