# Common Labels
labels:
  app: "pdf-v3"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "pdf-v3"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "pdf_v3_schema"
    image:
      repository: "pdf-v3-db"

# Container Configs
image:
  repository: "pdf-v3"
replicas: "1"
appType: "java-spring"
heap: "-Xmx1012m -Xms512m"
memory_limits: 1500Mi
memory_requests: 768Mi
healthChecks:
  enabled: true
  livenessProbePath: "/pdf-v3/health"
  readinessProbePath: "/pdf-v3/health"

# Additional Container Envs
env: |
  - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: "update"
  - name: SPRING_FLYWAY_ENABLED
    value: "true"
  - name: REDIS_HOST
    value: "redis.backbone"
  - name: REDIS_PORT
    value: "6379"
  - name: REDIS_CACHE_TTL_MINUTES
    value: "60"
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: "pdf-service-group"
  - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
    value: "earliest"
  - name: SERVER_PORT
    value: "8080"
  - name: EGOV_FILESTORE_HOST
    value: "https://digit-lts.digit.org/filestore/v3/files"
  - name: PLAYWRIGHT_HEADLESS
    value: "true"
  - name: PLAYWRIGHT_PAGE_WIDTH
    value: "8.27in"
  - name: PLAYWRIGHT_PAGE_HEIGHT
    value: "11.69in"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  
