{{- $root := . -}}
{{- $t := .Values.temporal -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamic-config
  namespace: {{ $t.namespace }}
  labels:
    {{- include "temporal.labels" $root | nindent 4 }}
    component: dynamic-config
data:
  {{ $t.server.dynamicConfig.fileName }}: |
    {{- toYaml $t.server.dynamicConfig.config | nindent 4 }}
