{{- if .Values.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "clickhouse-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
  name: {{ include "clickhouse-operator.resourceName" (dict "suffix" "controller-manager-metrics-monitor" "context" $) }}
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - {{- if .Values.metrics.secure }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    {{- end }}
    path: /metrics
    port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
    scheme: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
    {{- if .Values.metrics.secure }}
    tlsConfig:
      serverName: {{ include "clickhouse-operator.resourceName" (dict "suffix" "metrics-service" "context" $) }}.{{ .Values.namespace }}.svc
      {{- if .Values.certManager.enable }}
      ca:
        secret:
          key: ca.crt
          name: metrics-server-cert
      cert:
        secret:
          key: tls.crt
          name: metrics-server-cert
      keySecret:
        key: tls.key
        name: metrics-server-cert
      insecureSkipVerify: false
      {{- else }}
      insecureSkipVerify: true
      {{- end }}
    {{- end }}
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end }}
