apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/egovernments/DIGIT-DevOps.git
    path: deploy-as-code/helm/charts/backbone-services/k6-operator
    targetRevision: digit-lts
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: k6-operator-system
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - CreateNamespace=true
