apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ include "novu.namespace" . }}
  labels:
{{- toYaml .Values.mongodb.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
  selector:
{{- toYaml .Values.mongodb.labels | nindent 4 }}
