{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ include "novu.namespace" . }}
  labels:
{{- toYaml .Values.mongodb.labels | nindent 4 }}
spec:
  accessModes:
{{- toYaml .Values.mongodb.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClassName }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName }}
  {{- end }}
{{- end }}
