{{- with index .Values "cluster-configs" "namespaces" }}
{{- $labels := .labels | default dict }}
{{- if .create }}
{{- range .values }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  {{- with index $labels . }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
