deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  limits_config:
    allow_structured_metadata: true
    reject_old_samples: true
    volume_enabled: true
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      cache_ttl: 24h
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      cache_location: /var/loki/tsdb-cache
      cache_ttl: 24h
    filesystem:
      directory: /var/loki/chunks
  compactor:
    working_directory: /var/loki/boltdb-shipper-compactor
    retention_enabled: true
    delete_request_store: filesystem
  analytics:
    reporting_enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

minio:
  enabled: false

test:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false
