apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ include "novu.namespace" . }}
  labels:
{{- toYaml .Values.redis.labels | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
{{- toYaml .Values.redis.labels | nindent 6 }}
  template:
    metadata:
      labels:
{{- toYaml .Values.redis.labels | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          {{- if .Values.redis.probes.enabled }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.liveness.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.readiness.failureThreshold }}
          {{- end }}
          {{- with .Values.redis.resources }}
          resources:
{{- toYaml . | nindent 12 }}
          {{- end }}
