variable "name" {}
variable "node_count" {}
variable "vm_size" {}
variable "client_id" {}    
variable "client_secret" {}
variable "resource_group" {}
variable "location" {}
variable "environment" {}
variable "ssh_public_key" {}