#!/usr/bin/env python3
"""Generate a merged "modulith bundle" Helm chart from a digit3 bundle manifest.

The same <bundle>.package.yaml that drives digit3's generate_bundle.py (which
composes the application jar) drives this generator on the DevOps side: the
manifest's service list says which per-service Helm charts get merged into one
bundle chart.

    python3 generate_bundle_chart.py --manifest /path/to/dev-bundle.package.yaml

For each service the generator resolves the chart directory (<name>-java, then
<name>, across every charts/* group), renders it with `helm template` so all
`env: |` template strings resolve exactly as they would at deploy time, and
harvests the container env and the db-migration init container. Envs are merged
under the policy in merge-rules.yaml (optionally extended by a `helm:` section
in the manifest); same-name-different-value conflicts that no rule resolves are
reported and first-in-manifest-order wins.

The generated chart differs from the per-service charts in one deliberate way:
env is a MAP (name -> {value|valueFrom}), not a string block. Helm deep-merges
maps from the environment values file, so any single variable can be overridden
per environment under the bundle's own block (the per-service charts' string
blocks can only be replaced wholesale). Setting a variable to null removes it.

Everything under the output chart is generator-owned; edit the manifest or
merge-rules.yaml and re-run.
"""

import argparse
import copy
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
DEFAULT_CHARTS_ROOT = HERE.parent / "charts"
CHART_NAME_CANDIDATES = ("{name}-java", "{name}")

GENERATED_BANNER = (
    "# GENERATED by deploy-as-code/helm/bundler/generate_bundle_chart.py from {manifest} —\n"
    "# edit the manifest or bundler/merge-rules.yaml and re-run; do not edit this file.\n"
)


def die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def load_yaml(path):
    with open(path) as f:
        return yaml.safe_load(f)


# ── chart resolution ─────────────────────────────────────────────────────────

def resolve_chart(charts_root, service_name):
    """Find the chart directory for a manifest service name."""
    for group in sorted(p for p in charts_root.iterdir() if p.is_dir()):
        for cand in CHART_NAME_CANDIDATES:
            chart_dir = group / cand.format(name=service_name)
            if (chart_dir / "Chart.yaml").exists():
                return chart_dir
    return None


# ── rendering member charts ──────────────────────────────────────────────────

def render_deployment(chart_dir, common_dir, scratch_root):
    """helm-template a member chart in a scratch copy and return its Deployment."""
    scratch = scratch_root / chart_dir.name
    shutil.copytree(chart_dir, scratch)
    # Vendor the common library chart so `helm template` needs no repo access.
    shutil.copytree(common_dir, scratch / "charts" / "common")
    cmd = [
        "helm", "template", chart_dir.name, str(scratch),
        "-s", "templates/deployment.yaml",
        "--set", "image.tag=SCRATCH",
        "--set", "initContainers.dbMigration.image.tag=SCRATCH",
        "--set", "global.domain=scratch.local",
        "--set", "global.setup=fullsetup",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        die(f"helm template failed for {chart_dir.name}:\n{res.stderr}")
    for doc in yaml.safe_load_all(res.stdout):
        if doc and doc.get("kind") == "Deployment":
            return doc
    die(f"no Deployment rendered for {chart_dir.name}")


def extract_main_env(deployment, chart_name):
    containers = deployment["spec"]["template"]["spec"].get("containers", [])
    main = next((c for c in containers if c.get("name") == chart_name), None)
    if main is None:
        main = containers[0]
    return main.get("env") or []


def extract_db_migration(deployment):
    inits = deployment["spec"]["template"]["spec"].get("initContainers") or []
    return next((c for c in inits if c.get("name") == "db-migration"), None)


# ── env merge machinery ──────────────────────────────────────────────────────

def env_list_to_specs(env_list):
    """[{name, value|valueFrom}] -> ordered [(name, spec-dict)]."""
    out = []
    for e in env_list:
        spec = {k: v for k, v in e.items() if k != "name"}
        out.append((e["name"], spec))
    return out


def canon(spec):
    return json.dumps(spec, sort_keys=True)


class MergePolicy:
    def __init__(self, rules, manifest_helm):
        rules = copy.deepcopy(rules or {})
        manifest_helm = copy.deepcopy(manifest_helm or {})
        self.drop_exact = {}
        self.drop_patterns = []
        for entry in (rules.get("drop") or []) + (manifest_helm.get("drop") or []):
            reason = entry.get("reason", "")
            if "name" in entry:
                self.drop_exact[entry["name"]] = reason
            elif "pattern" in entry:
                self.drop_patterns.append((re.compile(entry["pattern"]), reason))
        self.resolve = dict(rules.get("resolve") or {})
        self.resolve.update(manifest_helm.get("resolve") or {})
        self.contract_env = dict(rules.get("contractEnv") or {})
        self.contract_env.update(manifest_helm.get("contractEnv") or {})

    def drop_reason(self, name):
        if name in self.drop_exact:
            return self.drop_exact[name] or "dropped by rule"
        for rx, reason in self.drop_patterns:
            if rx.search(name):
                return reason or f"dropped by pattern {rx.pattern}"
        return None


def is_loopback(spec, bundled_chart_names):
    """Env sourced from egov-service-host for a bundled service, or a literal
    URL to a bundled service — the bundle jar already rewires these to
    localhost, and an env var would silently win over that property."""
    cm = (spec.get("valueFrom") or {}).get("configMapKeyRef") or {}
    if cm.get("name") == "egov-service-host" and cm.get("key") in bundled_chart_names:
        return True
    value = spec.get("value")
    if isinstance(value, str):
        for chart in bundled_chart_names:
            if re.search(rf"https?://{re.escape(chart)}([.:/]|$)", value):
                return True
    return False


def merge_envs(per_service_envs, policy, bundled_chart_names, report):
    """per_service_envs: [(service_name, [(env_name, spec)])] in manifest order."""
    merged = {}     # env name -> spec
    owners = {}     # env name -> first service that set it
    for svc, entries in per_service_envs:
        for name, spec in entries:
            reason = policy.drop_reason(name)
            if reason:
                report["dropped"].setdefault(name, {"reason": reason, "services": []})
                report["dropped"][name]["services"].append(svc)
                continue
            if is_loopback(spec, bundled_chart_names):
                report["dropped"].setdefault(
                    name, {"reason": "loopback: callee is inside the bundle", "services": []})
                report["dropped"][name]["services"].append(svc)
                continue
            if name not in merged:
                merged[name] = spec
                owners[name] = svc
                continue
            if canon(merged[name]) == canon(spec):
                continue
            if name in policy.resolve or name in policy.contract_env:
                resolution = policy.resolve.get(name) or policy.contract_env[name]
                merged[name] = resolution
                report["resolved"].setdefault(name, {
                    "resolution": resolution, "between": [owners[name]]})
                if svc not in report["resolved"][name]["between"]:
                    report["resolved"][name]["between"].append(svc)
            else:
                report["conflicts"].setdefault(name, {
                    "kept": {"service": owners[name], "spec": merged[name]},
                    "ignored": []})
                report["conflicts"][name]["ignored"].append({"service": svc, "spec": spec})
    # Contract env wins over anything a member declared under the same name.
    for name, spec in policy.contract_env.items():
        merged[name] = copy.deepcopy(spec)
    return merged


# ── chart emission ───────────────────────────────────────────────────────────

DEPLOYMENT_TEMPLATE = """{{- $name := include "common.name" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
{{- if eq (.Values.replicas | int) 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
{{- end }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
      {{- include "common.labels" . | nindent 8 }}
    spec:
      initContainers:
      {{- range $svc := .Values.dbMigrationOrder }}
      {{- $m := index $.Values.dbMigrations $svc }}
      {{- if and $m $m.enabled }}
      - name: "db-migration-{{ $svc }}"
        image: {{ template "common.image" (dict "Values" $.Values "repository" $m.image.repository "tag" $m.image.tag) }}
        imagePullPolicy: {{ $m.image.pullPolicy | default "IfNotPresent" }}
        env:
        {{- range $envName, $spec := $m.env }}
        {{- if $spec }}
          - name: {{ $envName | quote }}
          {{- if hasKey $spec "value" }}
            value: {{ $spec.value | quote }}
          {{- else if hasKey $spec "valueFrom" }}
            valueFrom:
              {{- toYaml $spec.valueFrom | nindent 14 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: {{ $name }}
          image: {{ template "common.image" (dict "Values" $.Values "repository" .Values.image.repository "tag" .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
      {{- if .Values.healthChecks.enabled }}
          readinessProbe:
          {{- tpl .Values.healthChecks.readinessProbe . | nindent 12 }}
          livenessProbe:
          {{- tpl .Values.healthChecks.livenessProbe . | nindent 12 }}
      {{- end }}
        {{- if .Values.lifecycle }}
          lifecycle:
          {{- toYaml .Values.lifecycle | nindent 12 }}
        {{- end }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.heap | quote }}
            - name: SERVER_PORT
              value: {{ .Values.httpPort | quote }}
        {{- range $envName, $spec := .Values.env }}
        {{- if $spec }}
            - name: {{ $envName | quote }}
          {{- if hasKey $spec "value" }}
              value: {{ $spec.value | quote }}
          {{- else if hasKey $spec "valueFrom" }}
              valueFrom:
                {{- toYaml $spec.valueFrom | nindent 16 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- if .Values.resources }}
          resources:
            {{- tpl .Values.resources . | nindent 12 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
"""

SERVICE_TEMPLATE = """apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.name" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else }}
  namespace: {{ .Values.namespace }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  selector:
{{- include "common.labels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.httpPort }}
    targetPort: {{ .Values.httpPort }}
"""

# One Ingress, one path per bundled service prefix. With ingress.zuul=true the
# backend stays kong-kong-proxy (same as every per-service chart today); Kong's
# own routes must point the corresponding prefixes at this chart's Service.
INGRESS_TEMPLATE = """{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.name" . }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- else }}
  namespace: {{ .Values.namespace }}
{{- end }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
{{- if .Values.ingress.waf.enabled }}
{{- toYaml .Values.ingress.waf.annotations | nindent 4 }}
{{- end }}
  labels:
{{- include "common.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
    {{- range .Values.ingress.contexts }}
      - backend:
      {{- if $.Values.ingress.zuul }}
          service:
            name: kong-kong-proxy
            port:
              number: 8000
      {{- else }}
          service:
            name: {{ template "common.name" $ }}
            port:
              number: {{ $.Values.httpPort }}
      {{- end }}
        path: /{{ . }}
        pathType: Prefix
    {{- end }}
{{- if ne .Values.global.setup "quickstart" }}
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: {{ .Values.global.domain }}-tls-certs
{{- end }}
{{- end }}
"""


def emit_chart(out_dir, manifest_path, bundle, services, merged_env,
               db_migrations, contexts):
    banner = GENERATED_BANNER.format(manifest=manifest_path.name)
    out_dir.mkdir(parents=True, exist_ok=True)
    tpl_dir = out_dir / "templates"
    if tpl_dir.exists():
        shutil.rmtree(tpl_dir)
    tpl_dir.mkdir()

    chart_yaml = {
        "apiVersion": "v2",
        "name": bundle["name"],
        "description": ("GENERATED merged modulith bundle chart "
                        f"({', '.join(s['name'] for s in services)})"),
        "version": "0.1.0",
        "appVersion": str(bundle.get("version", "0.1.0")),
        "dependencies": [
            {"name": "common", "version": "0.0.5", "repository": "file://../../common"},
        ],
    }
    (out_dir / "Chart.yaml").write_text(
        banner + yaml.safe_dump(chart_yaml, sort_keys=False))

    values = {
        "labels": {"app": bundle["name"], "group": "core"},
        "image": {"repository": bundle["name"]},
        "replicas": 1,
        "appType": "java",
        "httpPort": int(bundle.get("port", 8080)),
        "heap": "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0",
        "tracing-enabled": False,
        "healthChecks": {
            "enabled": False,
            "livenessProbePath": "/actuator/health/liveness",
            "readinessProbePath": "/actuator/health/readiness",
        },
        # One pod runs every bundled service; sized from the measured bundle
        # footprint, not the sum of the per-service charts.
        "resources": ("requests:\n"
                      "  cpu: \"500m\"\n"
                      "  memory: \"1Gi\"\n"
                      "limits:\n"
                      "  cpu: \"2\"\n"
                      "  memory: \"2Gi\"\n"),
        "ingress": {
            "enabled": True,
            "zuul": True,
            "contexts": contexts,
        },
        "env": merged_env,
        "dbMigrationOrder": [name for name, _ in db_migrations],
        "dbMigrations": {name: spec for name, spec in db_migrations},
    }
    values_header = banner + (
        "#\n"
        "# env is a MAP (name -> {value|valueFrom}); the environment values file\n"
        "# deep-merges it, so any single variable can be overridden (or removed by\n"
        f"# setting it to null) under the `{bundle['name']}:` block in\n"
        "# environments/<env>.yaml. Same for dbMigrations.<service>.image.tag.\n"
        "# JAVA_OPTS and SERVER_PORT are rendered from .Values.heap/.Values.httpPort.\n"
    )
    (out_dir / "values.yaml").write_text(
        values_header + yaml.safe_dump(values, sort_keys=False, width=100))

    (tpl_dir / "deployment.yaml").write_text(banner + DEPLOYMENT_TEMPLATE)
    (tpl_dir / "service.yaml").write_text(banner + SERVICE_TEMPLATE)
    (tpl_dir / "ingress.yaml").write_text(banner + INGRESS_TEMPLATE)


def emit_env_sample(out_dir, bundle, db_migrations):
    """A ready-to-paste block for environments/<env>.yaml."""
    lines = [
        f"# Sample environment override block for the {bundle['name']} chart —",
        "# paste into environments/<env>.yaml and fill in the image tags.",
        f"{bundle['name']}:",
        "  image:",
        f"    repository: {bundle['name']}",
        "    tag: \"<bundle-image-tag>\"",
        "  # Any single env var can be overridden (maps deep-merge):",
        "  # env:",
        "  #   DB_HOST: {value: \"postgres.egov\"}",
        "  #   TENANT_MIGRATION_ENABLED: {value: \"true\"}",
        "  #   FILESTORE_S3_SOURCE: {value: \"s3\"}    # flip a dev pin from the bundle jar",
        "  dbMigrations:",
    ]
    for name, spec in db_migrations:
        lines.append(f"    {name}:")
        lines.append(f"      image: {{repository: {spec['image']['repository']}, tag: \"<tag>\"}}")
    (out_dir / "env-block.sample.yaml").write_text("\n".join(lines) + "\n")


# ── report ───────────────────────────────────────────────────────────────────

def print_report(report, services, missing_migrations, context_mismatches):
    print("\n=== bundle chart generation report ===")
    print(f"services merged: {', '.join(s['name'] for s in services)}")
    if missing_migrations:
        print(f"no db-migration init container found for: {', '.join(missing_migrations)}")
    if context_mismatches:
        print("\nEXTERNAL PATH CHANGES — chart ingress.context vs manifest prefix")
        print("(Kong routes / clients using the old context must move to the manifest prefix):")
        for svc, chart_ctx, prefix in context_mismatches:
            print(f"  {svc}: chart served /{chart_ctx}, bundle serves {prefix}")
    if report["dropped"]:
        print(f"\ndropped env vars ({len(report['dropped'])}):")
        for name in sorted(report["dropped"]):
            info = report["dropped"][name]
            print(f"  {name}  [{', '.join(sorted(set(info['services'])))}]")
            print(f"      {info['reason']}")
    if report["resolved"]:
        print(f"\nconflicts resolved by rule ({len(report['resolved'])}):")
        for name, info in sorted(report["resolved"].items()):
            print(f"  {name}: {json.dumps(info['resolution'])}  "
                  f"(between {', '.join(info['between'])})")
    if report["conflicts"]:
        print(f"\nUNRESOLVED CONFLICTS ({len(report['conflicts'])}) — first-in-manifest-order won; "
              "add a `resolve:` entry to merge-rules.yaml (or `helm.resolve` in the manifest):")
        for name, info in sorted(report["conflicts"].items()):
            print(f"  {name}:")
            print(f"    kept   ({info['kept']['service']}): {json.dumps(info['kept']['spec'])}")
            for ig in info["ignored"]:
                print(f"    ignored ({ig['service']}): {json.dumps(ig['spec'])}")
    print("\nreminders:")
    print("  - remove the merged services from the Argo CD ApplicationSet and add the bundle entry")
    print("  - repoint egov-service-host keys for merged services at the bundle Service")
    print("  - Kong routes for the merged prefixes must target the bundle Service")


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--manifest", required=True, type=Path,
                    help="path to the digit3 bundle manifest (e.g. dev-bundle.package.yaml)")
    ap.add_argument("--charts-root", type=Path, default=DEFAULT_CHARTS_ROOT)
    ap.add_argument("--rules", type=Path, default=HERE / "merge-rules.yaml")
    ap.add_argument("--output", type=Path, default=None,
                    help="output chart dir (default charts/bundles/<bundle.name>)")
    args = ap.parse_args()

    manifest = load_yaml(args.manifest)
    bundle = manifest["bundle"]
    services = manifest["services"]
    policy = MergePolicy(load_yaml(args.rules), manifest.get("helm"))
    out_dir = args.output or (args.charts_root / "bundles" / bundle["name"])
    common_dir = args.charts_root / "common"
    if not (common_dir / "Chart.yaml").exists():
        die(f"common chart not found at {common_dir}")

    # Resolve every service to a chart before doing any work.
    resolved = []
    for svc in services:
        chart_dir = resolve_chart(args.charts_root, svc["name"])
        if chart_dir is None:
            die(f"no chart found for service '{svc['name']}' under {args.charts_root}")
        resolved.append((svc, chart_dir))
    bundled_chart_names = {chart_dir.name for _, chart_dir in resolved}

    report = {"dropped": {}, "resolved": {}, "conflicts": {}}
    per_service_envs = []
    db_migrations = []
    missing_migrations = []
    context_mismatches = []

    with tempfile.TemporaryDirectory(prefix="bundle-chart-") as scratch:
        scratch_root = Path(scratch)
        for svc, chart_dir in resolved:
            chart_values = load_yaml(chart_dir / "values.yaml") or {}
            deployment = render_deployment(chart_dir, common_dir, scratch_root)
            per_service_envs.append(
                (svc["name"], env_list_to_specs(extract_main_env(deployment, chart_dir.name))))

            prefix = svc.get("prefix", "/" + svc["name"])
            chart_ctx = ((chart_values.get("ingress") or {}).get("context") or "").strip("/")
            if chart_ctx and "/" + chart_ctx != prefix:
                context_mismatches.append((svc["name"], chart_ctx, prefix))

            mig = extract_db_migration(deployment)
            raw_mig = (chart_values.get("initContainers") or {}).get("dbMigration") or {}
            if mig is None or not raw_mig.get("enabled"):
                missing_migrations.append(svc["name"])
                continue
            mig_env = {name: spec for name, spec in env_list_to_specs(mig.get("env") or [])}
            db_migrations.append((svc["name"], {
                "enabled": True,
                "image": {
                    "repository": (raw_mig.get("image") or {}).get("repository",
                                                                   f"{chart_dir.name}-db"),
                    "tag": "",
                },
                "env": mig_env,
            }))

    merged_env = merge_envs(per_service_envs, policy, bundled_chart_names, report)
    contexts = [svc.get("prefix", "/" + svc["name"]).strip("/") for svc in services]

    emit_chart(out_dir, args.manifest, bundle, services, merged_env,
               db_migrations, contexts)
    emit_env_sample(out_dir, bundle, db_migrations)
    print(f"wrote {out_dir}")
    print_report(report, services, missing_migrations, context_mismatches)


if __name__ == "__main__":
    main()
