apiVersion: v2
name: debezium-postgres-connector-registrar
description: Periodically (re)registers the Debezium PostgreSQL source connector against the Kafka Connect REST API
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: common
  version: 0.0.5
  repository: file://../../common
