# Common Labels
labels:
  app: "idgen-java"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "idgen"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "idgen_schema"
    image:
      repository: "idgen-java-db"
    env: |
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: "SCHEMA_TABLE"
          value: {{ .Values.initContainers.dbMigration.schemaTable | quote }}
        - name: "FLYWAY_USER"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-username
        - name: "FLYWAY_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db
              key: flyway-password
        - name: JAVA_ENABLE_DEBUG
          value: "TRUE"
        - name: "FLYWAY_LOCATIONS"
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: flyway-locations
        - name: FLYWAY_SCHEMAS
          value: public
        - name: FLYWAY_DEFAULT_SCHEMA
          value: public

# Container Configs
image:
  repository: "idgen-java"
replicas: 1
appType: "java"
tracing-enabled: true # Assuming you want to keep tracing
healthChecks:
  enabled: false # Disabled as requested
  livenessProbePath: "/health"
  readinessProbePath: "/health"
# Resource configuration for Go service
resources: |
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1.5Gi"

# Additional Container Envs
env: |
  - name: HTTP_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /idgen
  - name: DB_HOST
    value: postgresql-lts.egov
  - name: DB_PORT
    value: "5432"
  - name: DB_SSL_MODE
    value: disable
  - name: DB_NAME
    value: postgres
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: db
  - name: OTEL_ENABLED
    value: "false"
  - name: OTEL_SERVICE_NAME
    value: idgen
  - name: OTEL_SERVICE_VERSION
    value: 1.0.0
  - name: OTEL_METRICS_ENABLED
    value: "false"
  - name: PROMETHEUS_PORT
    value: "9090"
  - name: OTEL_TRACES_SAMPLER_ARG
    value: "1.0"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: open-telemetry-opentelemetry-collector.monitoring.svc.cluster.local:4318
  - name: PUBSUB_ENABLED
    value: "false"
  - name: PUBSUB_TYPE
    value: redis
  - name: PUBSUB_TOPIC_CREATE_TENANT
    value: account-create-tenant
  - name: PUBSUB_TOPIC_CREATE_TEMPLATE
    value: idgen-create-template
  - name: PUBSUB_TOPIC_UPDATE_TEMPLATE
    value: idgen-update-template
  - name: PUBSUB_TOPIC_DELETE_TEMPLATE
    value: idgen-delete-template
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
    value: "true"
  - name: KAFKA_PARTITION_COUNT
    value: "1"
  - name: KAFKA_REPLICATION_FACTOR
    value: "1"
  - name: KAFKA_CONSUMER_GROUP
    value: idgen-service
  - name: REDIS_ADDRESS
    value: redis.backbone.svc.cluster.local:6379
  - name: REDIS_PASSWORD
  - name: REDIS_DB
    value: "0"
  - name: REDIS_CONSUMER_GROUP
    value: idgen-service
  - name: REDIS_CONSUMER_ID
    value: idgen-service-1
  - name: REDIS_RETENTION_DAYS
    value: "7"
  - name: REDIS_MAX_STREAM_LENGTH
    value: "1000000"
  - name: REDIS_CLEANUP_INTERVAL
    value: "86400"
  - name: SCHEMA_SEPARATION_MODE
    value: "false"
  - name: SCHEMA_SEPARATION_TOPIC
    value: account-migration
  - name: MIGRATION_FLYWAY_LOCATIONS
    value: filesystem:/opt/digit/db/migrations
  - name: MIGRATION_SCRIPT_PATH
    value: /opt/digit/migrate.sh
  - name: MIGRATION_FLYWAY_BIN
    value: /opt/flyway/flyway
  - name: MIGRATION_SCHEMA_TABLE
    value: idgen_schema
  - name: LOG_LEVEL
    value: info
  - name: CONSOLE_LOGS_ENABLED
    value: "true"
